### PR TITLE
Really basic PR Template file

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by jbjonesjr** [comment]
@nschonni want to add a slug about making sure your Organization includes one public repository as well?

Would also be good to provide a best practices section. I could imagine the list including:
- If a government project, your Organization's description should include a reference to your country/agency
- include a URL for your organization that links back to your organization or agency webpage

What else? I'm trying to think of things that make it easier to vet these orgs in the future.

Also can edit the file too if you'd prefer.

**Comment by nschonni** [comment]
Sure I can try to make the edits, but I did leave it open for maintainers to push changes too.

**Comment by nschonni** [comment]
@jbjonesjr I've integrated you text. This can always land and then be polished afterwards if you think this is a good enough base

**Comment by jbjonesjr** [comment]
:+1:

**Pull request merged**
