### PR TITLE
Add PSPC-SPAC-buyandsell

### PR DESCRIPTION
**Pull request by nschonni**
Thanks for the contribution! **Below** is a template that can make it easier when submitting your Organization:

**Your Organization**: _Public Services and Procurement Canada, buyandsell.gc.ca _  
**GitHub Organization url**: https://github.com/PSPC-SPAC-buyandsell  
**Country/Locality**: _Ontario, Canada_

Inclusion requirements:
- [x] Referenced account is an [Organization](https://github.com/github/government.github.com#add-organization) not a User^
- [x] If this is a government project, your Organization's description should include a reference to your country/agency.
- [x] Make sure your Organization includes at least one public repository
- [x] Please also include a URL for your organization that links back to your organization or agency homepage.
 
^ If you want to convert your account to an org, details can be found here: https://help.github.com/articles/converting-a-user-into-an-organization/
  
 :heart: GitHub Government Contributors

### CODE REVIEW

**Comment by jbjonesjr** [comment]
@nschonni That org name... woof! I'm going to merge, but would love to have a cleaner name if we can find some org admins.

image

Interesting seems similar to UK's Crown Commercial Services.

**Comment by nschonni** [comment]
Yeah, I'm not sure why it isn't under https://github.com/PSPC-SPAC but maybe they lost access to that org

**Comment by jbjonesjr** [comment]
whoa, i was more just talking about the name including both the English and french (?) names plus web addresses mashed into one string.

But also double good point about what happened to the other org? Hmmm

**Comment by nschonni** [comment]
Ah, the double barrelled name would be for the "Official Languages" policy

**Comment by jbjonesjr** [comment]
interesting. i feel like that sort of localization should be something GitHub does better.... i'll open an issue internally.

**Pull request merged**
