### PR TITLE
Fedramp lead show

### PR DESCRIPTION
**Pull request by mike421453**
This PR includes two updates to add FedRAMP back to government.github.com

1. Add form page and form thank you pages back
2. Add the box back to the home page

We are now FedRAMP authorized!

cc: @SRosenberg13 @sophshep @courtneyscharff

### CODE REVIEW

**Comment by mike421453** [comment]
@sophshep @jbjonesjr -
Any idea why Travis is failing?  I can't get it to load to see what is happening.  This is a pretty lightweight update but it is possible I missed something.

**Comment by jbjonesjr** [comment]
@mike421453 I can help you with this. some of it is on my side(maintaining the community contributions) and the rest is that we can't link to the FEDRamp pages without them being live, despite that's what the branch does.

I'll get the other errors out of the way for you later today

**Comment by SRosenberg13** [comment]
Hey All - 

We on track to get this resolved by EOD today? All pieces are launching tomorrow at 9 AM EST (FedScoop, DLT campaign, and our internal campaign) routing to government.github.com/fedramp so want to make sure we are good. 

I am assuming this is what you are attempting to revert but wanted to share this PR with you all for context in hiding the pages a while back. Ignore me if this is what is being worked. 

https://github.com/github/government.github.com/pull/714

We can make the site live whenever - doesn't need to go live right as we launch. 

cc: @mike421453 @jbjonesjr @courtneyscharff

**Comment by jbjonesjr** [comment]
Yep, i'm almost done unblocking @mike421453 . At least from my perspective.

**Comment by jbjonesjr** [comment]
So at this point, the last build was 🍏 other than the changes that Mike is literally pushing live in this PR.  Visiting the site on review lab shows that the CTA is there, and the pages are good to go.

Despite travis being ... ahem, overly aggressive ... I'm going to `Admin Merge` this in. 

🎉 Happy **FedRAMP** everyone!! 🎉
If you're in DC and want to celebrate, i'm alllllllll game!

**Comment by mike421453** [comment]
woohoo!!!!!!!!!!!

**Pull request merged**
