### PR TITLE
Move organizations to a datafile

### PR DESCRIPTION
**Pull request by parkr**
Contingent on GH Pages moving up to Jekyll v1.3.0 or greater.

### CODE REVIEW

**Comment by troyswanson** [comment]
Don't forget to update `readme.md` (line 34) and `community.md` (line 32) with new instructions on how to add an organization to the list :wink:

**Comment by troyswanson** [comment]
If this gets merged, #176 will need to be re-done to use this new data file.

**Comment by XhmikosR** [comment]
:+1: 

This fixes  https://github.com/github/government.github.com/issues/162.

**Comment by benbalter** [comment]
@parkr would love to get this merged in. Mind merging in master as a few things have changed?
1. You'll probably want to grab a fresh `_config.yml` as there was a bit of reorganization there
2. Assuming `organizations.json` is going to be where the conflict is

**Comment by parkr** [comment]
@benbalter Donezo. You'll want to do a quick `bundle update` to get `github-pages v10` with Jekyll 1.3.0. Currently locked to v8.

**Comment by benbalter** [comment]
@parkr :metal:. Even took care of the docs and script. Thanks for the pull request.

6947808 bumps the dependency.

**Comment by parkr** [comment]
:+1: thanks!

**Comment by troyswanson** [comment]
:clap:

**Pull request merged**
