### PR TITLE
Update governments.yml

### PR DESCRIPTION
**Pull request by leifj**
Add sunet.se (part of the swedish research council) and swedenconnect.se (part of digg.se)

Thanks for the contribution! **Below** is a template that can make it easier when submitting your Organization:

**Your Organization**: Sunet  and SwedenConnect
**GitHub Organization url**: _@sunet_  _@swedenconnect_
**Country/Locality**: _Stockholm, Sweden_

the two URLs are 

https://sunet.se (a part of the Swedish Research Council)
https://swedenconnect.se (a joint project from digg.se and sunet.se)

Inclusion requirements:
- [x] Referenced account is an [Organization](https://github.com/github/government.github.com#add-organization) not a User^
- [x] If this is a government project, your Organization's description should include a reference to your country/agency.
- [x] Make sure your Organization includes at least one public repository
- [x] Please also include a URL for your organization that links back to your organization or agency homepage.

^ If you want to convert your account to an org, details can be found here: https://help.github.com/articles/converting-a-user-into-an-organization/
  
 :heart: GitHub Government Contributors

### CODE REVIEW

**Comment by nschonni** [comment]
Are these actually government organizations or Civic Tech orgs?

**Comment by leifj** [comment]
Sunet is the national research and education network and part of the Swedish Research Council (eg NSF) which is a govt. agency. SwedenConnect is similarly a project within another goverment agency digg.se - Swedish Agency for Digital Government. So yes: both are goverment organizations.

**Comment by leifj** [comment]
These are the parent orgs: https://vr.se (for sunet) and https://digg.se (for swedenconnect.se)

**Comment by leifj** [comment]
https://www.vr.se/english/about-us.html links to sunet (under other websites)

**Review by hi-artem — APPROVED** [review]

**Review by ejcheng — APPROVED** [review]

**Pull request merged**
