### PR TITLE
Add TRANSCOM and recategorize other military orgs

### PR DESCRIPTION
**Pull request by dynamike**
Thanks for the contribution! **Below** is a template that can make it easier when submitting your Organization:

**Your Organization**: United States Transportation Command
**GitHub Organization url**: @transcom
**Country/Locality**: US

Inclusion requirements:
- [x] Referenced account is an [Organization](https://github.com/github/government.github.com#add-organization) not a User^
- [x] If this is a government project, your Organization's description should include a reference to your country/agency.
- [x] Make sure your Organization includes at least one public repository
- [x] Please also include a URL for your organization that links back to your organization or agency homepage.
 
^ If you want to convert your account to an org, details can be found here: https://help.github.com/articles/converting-a-user-into-an-organization/
  
 :heart: GitHub Government Contributors

### CODE REVIEW

**Comment by nschonni** [comment]
Wondering from the URL if it makes more sense under "U.S. Military and Intelligence:"

**Comment by dynamike** [comment]
That makes sense. I think I got confused by `defense-cyber-crime-center` and `deptofdefense`. Both also apply to `U.S. Military and Intelligence`.

**Comment by mlinksva** [comment]
Regarding the recategorization of the two existing orgs: I know little of the ontology of US federal orgs, and would love to be corrected by someone who knows more -- I wonder if deptofdefense (top level) _has_ military agencies rather than _is_ one, eg https://en.wikipedia.org/wiki/United_States_Department_of_Defense#Military_Departments ?

I suppose nobody will care either for the purposes of this repo/site. Will merge after giving a day for any further input.

**Comment by dynamike** [comment]
reminder ping on this PR. Let me know if there's anything I need to add or change.

**Pull request merged**
