### PR TITLE
Work in progress: accessibility page

### PR DESCRIPTION
**Pull request by benbalter**
:warning: **WORK IN PROGRESS** :warning:

This pull request spikes out the initial structure of a potential `/accessibility` page describing GitHub.com, GitHub Enterprise, GitHub for Mac and GitHub for Window's compliance with §508 accessibility standards. The information in the pull request is to be considered an ongoing draft until merged if merged at all.

The format is adopted from the industry-standard [voluntary product accessibility template (VPAT)](http://www.state.gov/m/irm/impact/126343.htm). There's some more background on [the itic site](http://www.itic.org/public-policy/accessibility):

> The Voluntary Product Accessibility Template®, or VPAT®, is a tool used to document a product's conformance with the accessibility standards under Section 508 of the Rehabilitation Act. The purpose of the VPAT is to assist Federal contracting officials and other buyers in making preliminary assessments regarding the availability of commercial "Electronic and Information Technology" products and services with features that support accessibility. 

[Firefox](http://www.mozilla.org/en-US/firefox/vpat-2.html) has a great example of a VPAT written for Humans that we can emulate in part.

Much of the content still needs to be fleshed out, and it may make sense to loop in particular teams for some of the questions below.

### CODE REVIEW

**Comment by benbalter** [comment]
Here's what it looks like in its current state:

screen shot 2013-11-22 at 4 56 22 pm

**Comment by nschonni** [comment]
May also want to take a look at http://wet-boew.github.io/wet-boew/demos/arb-rra/arb-rra-en.html as it maps WCAG standards which are more international.

**Comment by benbalter** [comment]
@nschonni Great idea, although for this particular use case, we also need to be directly responsive to the VPAT request. Do you happen to know of any resources that crosswalk WCAG and §508?

**Comment by nschonni** [comment]
Nope, sorry

**Comment by benbalter** [comment]
Reopened over in #258.

**Pull request merged**
