### PR TITLE
Update _config.yml

### PR DESCRIPTION
**Pull request by parfenov**
OKF Ireland

### CODE REVIEW

**Comment by nschonni** [comment]
Should probably be under the "Civic Hackers" section like the rest of the OKF\* organizations

**Comment by jlord** [comment]
Yep, @parfenov will you put it under Civic Hackers since it is not an official government account? Thanks for submitting!

**Comment by parfenov** [comment]
I think it's done.

**Comment by jlord** [comment]
Thanks @parfenov!

**Pull request merged**
