### PR TITLE
Add Fukushima Lab.

### PR DESCRIPTION
**Pull request by psjnek**
**Your Organization**: _Nagoya Institute of Technology_  
**GitHub Organization url**: _@fukushimalab_  
**Country/Locality**: _Nagoya, Japan_
**Link**: _https://fukushima.web.nitech.ac.jp/_

Inclusion requirements:
- [x] Referenced account is an [Organization](https://github.com/github/government.github.com#add-organization) not a User^
- [x] If this is a government project, your Organization's description should include a reference to your country/agency.
- [x] Make sure your Organization includes at least one public repository
- [x] Please also include a URL for your organization that links back to your organization or agency homepage.
  
 :heart: GitHub Government Contributors

### CODE REVIEW

**Comment by mlinksva** [comment]
Thanks @WebSnke for all your PRs. If you have a methodology for finding missing government orgs and/or you're doing this as part of a larger project/with some objective, I'd be curious to learn about it! But thanks in any case, no need to respond.

I'm going to leave open PRs that are failing the alphabetization test (which also can fail due to extra spaces, like this one) as motivation to fix #991 but feel free to make pass manually and I'll merge when you do.

**Comment by WebSnke** [comment]
> I'm going to leave open PRs that are failing the alphabetization test (which also can fail due to extra spaces, like this one) as motivation to fix #991 but feel free to make pass manually and I'll merge when you do.

The tests seem to fail when new countries are added...

**Comment by mlinksva** [comment]
I suspect autocorrection will work after adding the actions bot as a maintainer to `github/government.github.com`:

```
  Error: Error: Pushing to https://github.com/WebSnke/government.github.com
  remote: Permission to WebSnke/government.github.com.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/WebSnke/government.github.com/': The requested URL returned error: 403
```

Will try to do that next week.

**Comment by psjnek** [comment]
> Will try to do that next week.

Great, I will submit a few entries in the meantime which won't fail.

**Comment by psjnek** [comment]
> Thanks @WebSnke for all your PRs. If you have a methodology for finding missing government orgs and/or you're doing this as part of a larger project/with some objective, I'd be curious to learn about it! But thanks in any case, no need to respond.

Haha, I contribute to open source projects as I would like to become a web developer myself once I graduate.

**Comment by psjnek** [comment]
> I suspect autocorrection will work after adding the actions bot as a maintainer to `github/government.github.com`:

The same problem also seems to occurs on [#1002](https://github.com/github/government.github.com/actions/runs/3911757390/jobs/6685511563).

**Comment by mlinksva** [comment]
Had another idea to have action make a suggested edit, which also seems to be failing due to some kind of permissions error. Will try again next time I have some free time, thanks for your patience.

**Pull request closed without merging**
