### PR TITLE
Added Belgian Police

### PR DESCRIPTION
**Pull request by tomjanssens**

### CODE REVIEW

**Comment by jlord** [comment]
Awesome! Thanks @tomjanssens. Do you know if this is the official GitHub account managed by the Belgian Police? We usually like to see an official government email associated with the account to verify.

**Comment by tomjanssens** [comment]
Thanks for your quick reply @jlord. Since I'm working as a consultant for the Belgian Police, on the [Internet Platform repository](https://github.com/belgianpolice/internet-platform), I do not have an official government email address.

Maybe the matching between [the screenshot in the repository README](https://github.com/belgianpolice/internet-platform) and http://www.police.be/leuven is a verification option?

**Comment by tomjanssens** [comment]
@jlord One of the internal police developers, who is also a member of the Github organisation, has added his official government email address to his [Github account](https://github.com/jowillems). Hope this helps the verification process.

**Comment by jlord** [comment]
Awesome, thanks for taking the time @tomjanssens!

**Pull request merged**
