### PR TITLE
Update governments.yml

### PR DESCRIPTION
**Pull request by dylanbeaudette**
Adding USDA-NRCS government entity. The only organization I know of is https://github.com/ncss-tech

### CODE REVIEW

**Comment by dylanbeaudette** [comment]
Noticed a typo and fixed it.

**Comment by nschonni** [comment]
This needs to be reverted because it's a user not an organization

**Comment by jbjonesjr** [comment]
based on the message, it looks like the Organization, NCSS-Tech, is the github home for NCSS. Any interest in adjusting the name of the org to include usda to make it a bit more discoverable? I've been working with various govt agencies on more of a standardization for their org names.

Either something like `USDA-NCSS-Tech`, or just `USDA-NCSS`? cc/ @smroecker

**Comment by jbjonesjr** [comment]
Or maybe even the more official name involves `USDA-NRCS`?

**Comment by dylanbeaudette** [comment]
@jbjonesjr Thanks for following up on this. 

The USDA-NRCS (agency) currently has no "official" repository. The National Cooperative Soil Survey (NCSS) is a collaboration between state and federal government agencies along with universities. There is no official "home" for the NCSS, however, USDA-NRCS staff typically organize events and lead the way. The NCSS-Tech repository was our first attempt at moving some of our work to a place were all cooperators (the "C" in NCSS) can contribute.

So, the rationale for my pull request:

1. ensure that "USDA-NRCS" is listed among government users of GitHub
2. provide a link to our "most representative" organization (NCSS-Tech) until such time that there is a more "official" presence on GitHub.

@nschonni Note that NCSS-Tech is run by USDA-NRCS employees, on government time: therefore this is a government organization run for the purposes of NRCS/NCSS business.

Thanks,
Dylan

**Comment by nschonni** [comment]
@dylanbeaudette `USDA-NRCS` is a GitHub user, not a GitHub horganization account, so it was breaking the build. See https://github.com/github/government.github.com/pull/506#issuecomment-267319919 for info on converting a user to a organization

**Pull request merged**
