### PR TITLE
Added accounts from some dutch government institutions

### PR DESCRIPTION
**Pull request by vandenoever**

### CODE REVIEW

**Comment by benbalter** [comment]
@vandenoever this is great. Thank you. It looks like there's no set format for government domains, is there? Is there a (semi) official list of government domains that you know of?

**Comment by vandenoever** [comment]
https://overheid.nl is a key government domain (overheid = government).
https://almanak.overheid.nl/ lists government institutions such as ministries, provinces, parliament etc. and provides links to the websites.

**Comment by benbalter** [comment]
Thanks @vandenoever it doesn't look like there's any programmatic way to grab those domains, but [I added `overheid.nl` to this list](https://github.com/benbalter/gman/pull/96) to look out for.

**Comment by vandenoever** [comment]
```
env -u https_proxy wget -r -np https://almanak.overheid.nl/
grep @ -rI almanak.overheid.nl/|cut -f 2 -d @|cut -f 1 -d '"'|grep \\.nl$|sort|uniq
```

gives you a good list, mostly municipalities (gemeente), but also ministeries

```
aaenhunze.nl
aaenmaas.nl
aalburg.nl
aalsmeer.nl
aalten.nl
achtkarspelen.nl
acvz.minbzk.nl
adviesorgaan-rmo.nl
agentschaptelecom.nl
alblasserdam.nl
albrandswaard.nl
alkmaar.nl
almelo.nl
almere.nl
alphenaandenrijn.nl
alphen-chaam.nl
ameland.nl
amersfoort.nl
amstelveen.nl
apeldoorn.nl
appingedam.nl
arnhem.nl
assen.nl
asten.nl
baarle-nassau.nl
baarn.nl
barendrecht.nl
barneveld.nl
bedum.nl
beesel.nl
bellingwedde.nl
bergeijk.nl
bergen-nh.nl
bergen.nl
bergenopzoom.nl
beuningen.nl
beverwijk.nl
bij12.nl
binnenmaas.nl
bladel.nl
blaricum.nl
bloemendaal.nl
bodegraven-reeuwijk.nl
boekel.nl
borger-odoorn.nl
borne.nl
borsele.nl
boxmeer.nl
boxtel.nl
bprbzk.nl
brabant.nl
brabantsedelta.nl
brandweerflevoland.nl
breda.nl
brielle.nl
bronckhorst.nl
brummen.nl
brunssum.nl
bunnik.nl
buren.nl
bussum.nl
bwbrabant.nl
caop.nl
capelleaandenijssel.nl
castricum.nl
ccmo.nl
ceg.nl
cibg.nl
ciot.justid.nl
coevorden.nl
cpb.nl
cranendonck.nl
cromstrijen.nl
cuijk.nl
culemborg.nl
cvz.nl
dalfsen.nl
debilt.nl
delfzijl.nl
demarne.nl
denhelder.nl
derondevenen.nl
destadsregio.nl
deurne.nl
deventer.nl
dewolden.nl
dgv.minvenj.nl
diemen.nl
dinkelland.nl
doesburg.nl
doetinchem.nl
dommel.nl
dongen.nl
dongeradeel.nl
drechterland.nl
drechtsteden.nl
drenthe.nl
drimmelen.nl
dronten.nl
druten.nl
dtv.minbzk.nl
dtv.minjus.nl
duiven.nl
echt-susteren.nl
edam-volendam.nl
ede.nl
eemnes.nl
eemsmond.nl
eersel.nl
eerstekamer.nl
eijsden-margraten.nl
eindhoven.nl
elburg.nl
emissieautoriteit.nl
emmen.nl
enkhuizen.nl
enschede.nl
epe.nl
ermelo.nl
etten-leur.nl
ferwerderadiel.nl
flevoland.nl
franekeradeel.nl
fryslan.nl
fumo.nl
gbtwente.nl
gdi.minvenj.nl
GDI.minvenj.nl
geertruidenberg.nl
gelderland.nl
geldermalsen.nl
geldrop-mierlo.nl
gembest.nl
gemeentebeek.nl
gemeenteberkelland.nl
gemeentehulst.nl
gemeentelangedijk.nl
gemeentemaasgouw.nl
gemeente-mill.nl
gemeentenoordenveld.nl
gemeente-oldambt.nl
gemeentesluis.nl
gemeente-steenbergen.nl
gemeentestein.nl
gemeentewesterveld.nl
gemeentewestland.nl
gemert-bakel.nl
gemhg.nl
gennep.nl
ghornml.nl
giessenlanden.nl
gilzerijen.nl
goeree-overflakkee.nl
goes.nl
goirle.nl
Gorinchem.nl
gouda.nl
grave.nl
grdebevelanden.nl
gr.nl
groesbeek.nl
groningen.nl
grootegast.nl
gulpen-wittem.nl
haaksbergen.nl
haaren.nl
Haarlemmerliede.nl
haarlemmermeer.nl
haarlem.nl
halderberge.nl
hardenberg.nl
harderwijk.nl
haren.nl
harlingen.nl
hattem.nl
hdsr.nl
heemskerk.nl
heemstede.nl
heerde.nl
heerenveen.nl
heerhugowaard.nl
heerlen.nl
heeze-leende.nl
heiloo.nl
hellendoorn.nl
hellevoetsluis.nl
helmond.nl
hengelo.nl
hetbildt.nl
heumen.nl
heusden.nl
heuvelrug.nl
hhdelfland.nl
hhnk.nl
hhsk.nl
h-i-ambacht.nl
hillegom.nl
hilvarenbeek.nl
hilversum.nl
hlt.halt.nl
hofvantwente.nl
hogeraadvanadel.nl
hollandskroon.nl
hollands-midden.nl
hoogeveen.nl
hoogezand-sappemeer.nl
hoorn.nl
horstaandemaas.nl
houten.nl
huizen.nl
hunzeenaas.nl
huurcommissie.nl
hvd-drenthe.nl
hvdgm.nl
igsd-sw.nl
igz.nl
ijsselstein.nl
ind.minbzk.nl
ind.minjus.nl
inspectiejz.nl
inspectievenj.nl
ipo.nl
ismh.nl
isw.nl
justid.nl
kaagenbraassem.nl
kabinetvandekoning.nl
kampen.nl
kanselarij.nl
kapelle.nl
katwijk.nl
kerkrade.nl
kiesraad.nl
kinderbescherming.nl
koggenland.nl
kollumerland.nl
korendijk.nl
krimpenaandenijssel.nl
krimpenerwaard.nl
laarbeek.nl
landerd.nl
landgraaf.nl
Landsmeer.nl
lansingerland.nl
laren.nl
leek.nl
leerdam.nl
leeuwarden.nl
leeuwarderadeel.nl
leiderdorp.nl
leidschendam-voorburg.nl
lelystad.nl
leudal.nl
leusden.nl
lingewaal.nl
lingewaard.nl
lisse.nl
littenseradiel.nl
lochem.nl
logius.nl
Logius.nl
loonopzand.nl
lopik.nl
loppersum.nl
losser.nl
loyalis.nl
maasdriel.nl
maassluis.nl
maastricht.nl
marum.nl
medemblik.nl
meerschap-paterswolde.nl
meerssen.nl
menameradiel.nl
menterwolde.nl
meppel.nl
middelburg.nl
middendelfland.nl
middendrenthe.nl
midnef.nl
miinvws.nl
milieudienst-ijmond.nl
minaz.nl
minbuza.nl
minbzk.nl
mindef.nl
minez.nl
minfin.nl
minjus.nl
minlnv.nl
minvenj.nl
minvws.nl
moerdijk.nl
montfoort.nl
mookenmiddelaar.nl
mrdh.nl
muiden.nl
mzhz.nl
naarden.nl
nationaleombudsman.nl
nederbetuwe.nl
nederweert.nl
neerijnen.nl
nfi.minvenj.nl
nieuwegein.nl
nieuwkoop.nl
nijmegen.nl
nissewaard.nl
nmanet.nl
noord-beveland.nl
noorderzijlvest.nl
noord-holland.nl
noordoostpolder.nl
noordwijkerhout.nl
noordwijk.nl
nuenen.nl
nunspeet.nl
nuth.nl
nza.nl
odbn.nl
odmh.nl
oegstgeest.nl
oirschot.nl
oisterwijk.nl
oldebroek.nl
oldenzaal.nl
olst-wijhe.nl
ommen.nl
onderbanken.nl
oosterhout.nl
oostgelre.nl
ooststellingwerf.nl
oostzaan.nl
opmeer.nl
opsterland.nl
oss.nl
oud-beijerland.nl
oude-ijsselstreek.nl
ouder-amstel.nl
oudewater.nl
overbetuwe.nl
overijssel.nl
overmaas.nl
papendrecht.nl
parkstad-limburg.nl
pbl.nl
p-direkt.minbzk.nl
peelenmaas.nl
pekela.nl
pijnacker-nootdorp.nl
postbus51.nl
proinciegroningen.nl
provicniegroningen.nl
provinciegroningen.nl
provincie-utrecht.nl
prvlimburg.nl
purmerend.nl
putten.nl
pzh.nl
raadvanstate.nl
raalte.nl
rechspraak.nl
rechtspraak.nl
reclassering.nl
recreatieschapdrenthe.nl
reestenwieden.nl
regio-achterhoek.nl
regiofoodvalley.nl
regiogenv.nl
regionoordveluwe.nl
regiorivierenland.nl
regioutrecht.nl
regiowestelijkemijnstreek.nl
reimerswaal.nl
rekenkamer.nl
renkum.nl
renswoude.nl
reuseldemierden.nl
rgd.minbzk.nl
rheden.nl
rhenen.nl
ridderkerk.nl
rijksoverheid.nl
rijksvastgoedbedrijf.nl
rijnwaarden.nl
rijssen-holten.nl
rijswijk.nl
rivm.nl
rob-rfv.nl
roerdalen.nl
roermond.nl
rom-rijnmond.nl
roosendaal.nl
rotterdam.nl
rozendaal.nl
rsj.nl
rucphen.nl
schadefonds.nl
schagen.nl
scheldestromen.nl
scherpenzeel.nl
schiedam.nl
schiermonnikoog.nl
schijndel.nl
schinnen.nl
schouwen-duiveland.nl
scp.nl
servicebureaugemeenten.nl
servicepunt71.nl
s-hertogenbosch.nl
simpelveld.nl
sintanthonis.nl
sint-michielsgestel.nl
sint-oedenrode.nl
sittard-geleen.nl
slachtofferhulp.nl
sliedrecht.nl
slochteren.nl
smallingerland.nl
soest.nl
someren.nl
sonenbreugel.nl
sre.nl
sr.rotterdam.nl
staatsbosbeheer.nl
stadskanaal.nl
stadsregioamsterdam.nl
staphorst.nl
stedebroec.nl
steenwijkerland.nl
stichtsevecht.nl
strijen.nl
sudwestfryslan.nl
tcbodem.nl
t-diel.nl
tenboer.nl
terschelling.nl
texel.nl
teylingen.nl
tholen.nl
tiel.nl
tilburg.nl
toezichtkansspelen.nl
tubbergen.nl
tweedekamer.nl
twenterand.nl
tynaarlo.nl
uden.nl
uitgeest.nl
uithoorn.nl
urk.nl
utrecht.nl
uvw.nl
vaals.nl
valkenburg.nl
valkenswaard.nl
vallei-veluwe.nl
vb.amsterdam.nl
vechtstromen.nl
veendam.nl
veenendaal.nl
veere.nl
veghel.nl
veiligheidsregio-ijsselland.nl
veiligheidsregio-nhn.nl
veiligheidsregio-rr.nl
veldhoven.nl
velsen.nl
venlo.nl
venray.nl
vianen.nl
vlagtwedde.nl
vlieland.nl
vlissingen.nl
vno.minbzk.nl
vnw.minbzk.nl
voerendaal.nl
voorschoten.nl
voorst.nl
vrbn.nl
vrgz.nl
vrk.nl
vrtwente.nl
vru.nl
vrzeeland.nl
vrzhz.nl
vrzob.nl
vught.nl
vwa.nl
vz.minbzk.nl
waalre.nl
waalwijk.nl
waddinxveen.nl
wageningen.nl
wassenaar.nl
waterland.nl
waternet.nl
weert.nl
weesp.nl
werkendam.nl
westervoort.nl
westmaasenwaal.nl
weststellingwerf.nl
westvoorne.nl
wetterskipfryslan.nl
wgs.nl
wierden.nl
wijchen.nl
wijdemeren.nl
wijkbijduurstede.nl
winsum.nl
winterswijk.nl
wispa.nl
wmrijk.nl
woensdrecht.nl
woerden.nl
wormerland.nl
woudenberg.nl
woudrichem.nl
WPM.nl
wrij.nl
wshd.nl
wsrl.nl
wwi.minbzk.nl
zaltbommel.nl
zandvoort.nl
zederik.nl
zeeland.nl
zeevang.nl
zeewolde.nl
zeist.nl
zevenaar.nl
zoetermeer.nl
zoeterwoude.nl
zuiderzeeland.nl
zuidhorn.nl
zuidplas.nl
zundert.nl
zutphen.nl
zwartewaterland.nl
zwijndrecht.nl
zwolle.nl
```

Where is this list used? Do you use it to automatically get a list of government accounts? If so, I'd love to see the one for the Netherlands, since querying the search interface surely does not yield complete results.

**Comment by benbalter** [comment]
Wow. @vandenoever. This is great. Thank you. When a government agency doesn't give you an API, just download the entire website. Ha.

> Where is this list used?

It's part of an open source Ruby Gem called [Gman](https://github.com/benbalter/gman). Gman identifies if a given domain is government or not.

>  Do you use it to automatically get a list of government accounts? If so, I'd love to see the one for the Netherlands, since querying the search interface surely does not yield complete results.

It's used elsewhere, but we use it within GitHub for things like analytics, and I regularly go though to make sure the list of organizations here is up to date with those government organizations that have public profiles. Next time I update the list, I'll be sure to cc you if there are new `.nl` organizations.

**Comment by vandenoever** [comment]
Excellent, looking forward to it.

**Pull request merged**
