### PR TITLE
added the Web Experience Toolkit to the list of Canadian projects

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Comment by patcon** [comment]
:+1:

**Comment by nschonni** [comment]
@LaurentGoderre Any reason you forked this into the wet-boew org instead of your own?

**Comment by LaurentGoderre** [comment]
well it's the organization we are adding so..., beside I'm not sure we need to keep our fork after this...

**Comment by patcon** [comment]
Can't speak for how you guys roll, but cruising through an org and seeing any forked repos is a good way to gauge how that project engages with the outside community. But your mileage may vary.

**Pull request merged**
