### PR TITLE
Add @SGMAP to list of French GitHub users

### PR DESCRIPTION
**Pull request by MattiSG**

### CODE REVIEW

**Comment by MattiSG** [comment]
The Travis failure is:

```
  *  External link https://github.com/britishcolumbia.png failed: 404 No error
  *  External link https://github.com/britishcolumbia failed: 404 No error
  *  External link https://github.com/britishcolumbia failed: 404 No error
```

Ha… so BRITISH Columbia prevents France from entering this alliance? :suspect: :wine_glass:

**Comment by benbalter** [comment]
@MattiSG is @SGMAP government-owned? Looking at the billing email address, I'm unable to confirm that it's the official organization. As for the error, I'll get that cleaned up on master. Sorry for the hassle.

**Comment by MattiSG** [comment]
Billing email address changed. We are http://www.modernisation.gouv.fr.
See [some of our repos](https://github.com/sgmap/mes-aides-api) with a gouv.fr production address.
If you want, I can also send you an email from a gouv.fr address.

**Comment by MattiSG** [comment]
(but really, this “billing email address” thing looks bullshit, as I was able to change it without any confirmation)

**Comment by MattiSG** [comment]
Poke @benbalter.

**Comment by benbalter** [comment]
@MattiSG thanks for this. The billing address is one way to check governmentiness, and is the easiest to communicate in a public forum, but yes, you're absolutely right. Merging. :fr:

**Pull request merged**
