### PR TITLE
civic_hackers.yml updates

### PR DESCRIPTION
**Pull request by jcastle-zz**
Added a couple values based on validation of governments.yml.  My findings are reflected in the new yml file with rationale provided below.

- arcticlcc - nonprofit, moved to civic-hackers.yml
- opengovplatform - nonprofit, moved to civic-hackers.yml

### CODE REVIEW

**Comment by kipruto06** [comment]
Can you engage me  in validation of government

**Comment by jcastle-zz** [comment]
@kipruto06, did you want to chat outside of GH?  joseph.castle@gsa.gov

**Comment by kipruto06** [comment]
Yes I could love to share my issues outside

**Comment by nschonni** [comment]
This might need a rebase since it seems like a bunch of other changes got introduced

**Comment by kipruto06** [comment]
Universal laws are unchangeable

**Comment by froi** [comment]
Same here @jcastle, could we circle back to this?

**Comment by kipruto06** [comment]
Absolutely

**Comment by jcastle-zz** [comment]
@froi, this is pretty old now. I don't track this list, or haven't in over a year. I would go with what is on the site now.

**Comment by froi** [comment]
No worries @jcastle, thanks for the comment.

Closing due to inactivity and time.

**Pull request closed without merging**
