### PR TITLE
Fixing gov_cloud redirect

### PR DESCRIPTION
**Pull request by jbjonesjr**
redirect_to takes a string, not an array. that also makes total sense.

### CODE REVIEW

**Comment by akinaito** [comment]
@jbjonesjr Can you pls let @Kzweng @m0rgane know when you merge (or I guess now they'll get notification 😆 )  Just want to make sure it is a thing before confirming for AWS ad

**Comment by jbjonesjr** [comment]
@akinaito definitely. I hope this is all I need now. we'll see after the next pages build... :crossed_fingers:

**Comment by jbjonesjr** [comment]
WHYYYY.... 

please help @parkr , you're my only hope

**Comment by nschonni** [comment]
looks like it is supposed to be an array https://github.com/jekyll/jekyll-redirect-from#redirect-to

**Pull request merged**
