### PR TITLE
Updated U.S. gov't list with new USDA repos

### PR DESCRIPTION
**Pull request by jcastle-zz**
Thanks for the contribution! **Below** is a template that can make it easier when submitting your Organization:

**Your Organization**: U.S. General Services Administration - Code.gov  
**GitHub Organization url**: @jcastle  and @GSA/code-gov
**Country/Locality**: U.S./Washington, DC
**URL**: https://code.gov/

----
Received an updated USDA org list from my contact there. Added to master U.S. gov't list. Will try to keep this updated as I find more. Cheers federal team! ;-)

----
Inclusion requirements:
- [ ] Referenced account is an [Organization](https://github.com/github/government.github.com#add-organization) not a User^
- [ ] If this is a government project, your Organization's description should include a reference to your country/agency.
- [ ] Make sure your Organization includes at least one public repository
- [ ] Please also include a URL for your organization that links back to your organization or agency homepage.
 
^ If you want to convert your account to an org, details can be found here: https://help.github.com/articles/converting-a-user-into-an-organization/
  
 :heart: GitHub Government Contributors

### CODE REVIEW

**Comment by jcastle-zz** [comment]
Meant to tag @jbjonesjr or @froi.

**Comment by jcastle-zz** [comment]
Found one more US gov't org for Treasury. Thanks!

**Comment by jbjonesjr** [comment]
> Found one more US gov't org for Treasury. Thanks!

Just one more ? :troll:

Thank you @jcastle!

**Comment by jcastle-zz** [comment]
Have to get Jenkins working. I don't like the red "x" on my PRs.

**Pull request merged**
