### PR TITLE
Add SatelliteApplicationsCatapult to governments.yml

### PR DESCRIPTION
**Pull request by emilyselwood**
adding https://github.com/SatelliteApplicationsCatapult to governments.yml in the U.K. Central section

### CODE REVIEW

**Comment by benbalter** [comment]
@wselwood is Catapult a government entity?

**Comment by emilyselwood** [comment]
The Catapult is an independent technology and innovation company, which is partly funded by government. We are limited by guarantee, but receive a core grant from Innovate UK (Department of Innovation and Skills).

**Comment by benbalter** [comment]
That sounds more like [government funded research](https://github.com/github/government.github.com/blob/gh-pages/_data/research.yml) to me, than a government agency.

**Comment by emilyselwood** [comment]
Sorry for the delay getting back to you. Been out of the office for a while.

We are similar to the Met office which is why we went with that section. If you would rather we create a UK section in the research part that is no problem and I can amend this pull request.

**Comment by jbjonesjr** [comment]
@wselwood yes, i would definitely move it into the research section (logically it makes sense to fall under govt funded research). Are you still receiving govt funding?

**Comment by emilyselwood** [comment]
Created U.K section under research and moved  SatelliteApplicationsCatapult there.

Yes we still receive govt funding.

**Comment by jbjonesjr** [comment]
Thanks @wselwood ! Major help

**Pull request merged**
