### PR TITLE
Add Polish Ministry of Digital Affairs

### PR DESCRIPTION
**Pull request by KrzysiekJ**

### CODE REVIEW

**Comment by jbjonesjr** [comment]
Hey @KrzysiekJ , can you either update your fork, or allow collaborators to commit to your fork and I can make the update myself? Once complete, I think tests will pass and it can merge.

**Comment by KrzysiekJ** [comment]
Updated my fork, but there is still an error (“CoffeeScript is not defined”).

**Comment by jbjonesjr** [comment]
@KrzysiekJ that was an issue with upstream, that is now resolved (via #515).

**Comment by jbjonesjr** [comment]
one last update and you should be good. (of note, future PRs now include the ability to let contributors edit the fork, which would allow me to update the branch myself in the future).

**Comment by KrzysiekJ** [comment]
Thanks. I’ve updated the fork, build passed.

**Pull request merged**
