### PR TITLE
Updated with additional Canadian agencies

### PR DESCRIPTION
**Pull request by harsh**
@benbalter I noticed all 3 levels of Canadian governments are on this list (municipal, provincial, and federal).  I want to make sure I am capturing them correctly.  Also is this suppose to be all agencies or agencies we are prospecting?

### CODE REVIEW

**Comment by jbjonesjr** [comment]
@harsh it seems like `electionscanada` and `National Defense....` are no longer valid. What up with that? Wanna make an edit?

**Comment by harsh** [comment]
@jbjonesjr National Defence is a GHE customer and Elections Canada exists.  What is the check against?

**Comment by jbjonesjr** [comment]
@harsh GitHub.com organizations . www.github.com/electionscanada returns a 404.

For National Defense , this list has historically been focused on .com organizations. I'm shooting for a redesign (and additional features) in 2017 that would allow for additional segments, including Enterprise customers.

**Comment by harsh** [comment]
@jbjonesjr Looks like Elections Canada has a new URL: https://github.com/thezane/ca-elections

**Comment by harsh** [comment]
@jbjonesjr Sorry looks like the above is not owned by the Canadian government!

**Comment by harsh** [comment]
@jbjonesjr I noticed in the readme to create a fork when adding content to the government.yml file.  I just made a branch is that okay?

**Comment by jbjonesjr** [comment]
@harsh branch is fine! Thanks.

**Comment by nschonni** [comment]
Only the City of Toronto org is actually a Canadian government GH org. CRA is a random user, not the department

**Comment by harsh** [comment]
>Only the City of Toronto org is actually a Canadian government GH org. CRA is a random user, not the department

Thank you for the check @nschonni I removed all except for the City of Toronto

**Comment by nschonni** [comment]
The build failures are now just related to stuff already flagged in #518

**Pull request closed without merging**
