### PR TITLE
Add MIT License

### PR DESCRIPTION
**Pull request by sonalkr132**
Kinda ironic given https://github.com/blog/1964-open-source-license-usage-on-github-com :smile:

### CODE REVIEW

**Comment by nschonni** [comment]
@jbjonesjr is there a content license GitHub usually uses?

**Comment by jbjonesjr** [comment]
I think the issue here is that there is content used in this repository that GitHub does not own the copyright to, if I remember correctly.

**Comment by nschonni** [comment]
Note sure, but I guess this is another way to go https://github.com/github/choosealicense.com#license

**Comment by jbjonesjr** [comment]
didn't this come up last year sometime too? let me go explore

**Comment by jbjonesjr** [comment]
closing this out  we have no plan to license this. instead, enjoy the lack of license

**Pull request closed without merging**
