### PR TITLE
Fix quote about WET funding sources to match intent, transcript

### PR DESCRIPTION
**Pull request by randomecho**
The verbatim quote is [at 54:34 of the video](http://www.youtube.com/watch?v=zBLxKcLIIWg&t=54m34s)

> It's a... it's community resources [...]

But for the sake of clarity and grammar, should best be written as

> It's community resources [...]

### CODE REVIEW

**Comment by afeld** [comment]
Build failure wasn't you're doing, so we can address it separately.  Thanks!

**Comment by randomecho** [comment]
That's a relief. Was wondering why a Markdown file not touching anything else was flagging a build fail.

**Comment by afeld** [comment]
It's using [HTML::Proofer](https://github.com/gjtorikian/html-proofer) to test against live URLs, which unfortunately makes it non-deterministic.  Pros and cons.

**Comment by benbalter** [comment]
@afeld we could wrap HTML Proofer with [VCR](https://github.com/vcr/vcr)?

**Comment by afeld** [comment]
Good question... feels like it would kinda defeat the purpose, though?  Granted, if a URL goes away, then there's not a lot we can do besides remove the link.  I suppose all new links would be caught.

/cc @gjtorikian

**Comment by gjtorikian** [comment]
I'm not against such a configurable option (even though I personally wouldn't use it--consider every PR scanning through links a recheck of an often unchecked section of testing). I don't know how to work with the use case well enough to learn how to work the VCR (heh).

**Pull request merged**
