### PR TITLE
Add CivicTech Romania to the list

### PR DESCRIPTION
**Pull request by ClaudiuCeia**
https://civictech.ro/

### CODE REVIEW

**Review by nschonni — APPROVED** [review]

**Comment by ClaudiuCeia** [comment]
Hey @nschonni, thanks for approving. How long until these get merged and pushed to production? Thanks!

**Comment by nschonni** [comment]
Sorry I don't have the ability to merge in this repo.
I think @jbjonesjr is the only one maintaining this project right now.

**Comment by ClaudiuCeia** [comment]
Thanks @nschonni, good to know! :)

**Comment by jbjonesjr** [comment]
thanks for the contribution @ClaudiuCeia

**Pull request merged**
