### PR TITLE
Streetmix image + grammar.

### PR DESCRIPTION
**Pull request by mwichary**
Add better Streetmix image and change centering of images so that it looks better on the homepage. Also, small grammar changes.

### CODE REVIEW

**Comment by mwichary** [comment]
Before:
1-before

After:
1-after

**Comment by jlord** [comment]
I'm sitting next to @mwichary and :thumbsup: approve of the style updates that only change a little how the other images are displayed but help a lot for more narrow images like the Streetmix one.

@benbalter there is a small grammar update too if you want to :eyes: that.

**Comment by mwichary** [comment]
Awesome site, BTW.

**Comment by benbalter** [comment]
@mwichary :metal: thanks for taking the time to put the pull request together. A huge improvement.

**Pull request merged**
