### PR TITLE
Add StatCan org

### PR DESCRIPTION
**Pull request by nschonni**
Thanks for the contribution! **Below** is a template that can make it easier when submitting your Organization:

**Your Organization**: Statistics Canada  
**GitHub Organization url**: @StatCan
**Country/Locality**: Ottawa, Ontario, Canada

Inclusion requirements:
- [x] Referenced account is an [Organization](https://github.com/github/government.github.com#add-organization) not a User^
- [ ] If this is a government project, your Organization's description should include a reference to your country/agency.
- [x] Make sure your Organization includes at least one public repository
- [x] Please also include a URL for your organization that links back to your organization or agency homepage.
 
^ If you want to convert your account to an org, details can be found here: https://help.github.com/articles/converting-a-user-into-an-organization/
  
 :heart: GitHub Government Contributors

/cc @LaurentGoderre

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
:+1:

**Comment by jbjonesjr** [comment]
kind of jealous of all the fun things happening in Canada these days!

**Comment by LaurentGoderre** [comment]
@jbjonesjr grass is always greener on the other side of the fence. The US Gov has a lot of talent and cool initiative. I just wish we could work together more.

**Comment by jbjonesjr** [comment]
Here's the deal. I'll advocate for better working if you return `aaron snow` 😛

**Comment by LaurentGoderre** [comment]
Oh come on! let us have him for a while at least! :stuck_out_tongue:

**Pull request merged**
