### PR TITLE
Bump the ruby version and patch upstream bundler version issue

### PR DESCRIPTION
**Pull request by nschonni**
Travis seemed to have some trouble so this is an attempt to see if it is version related

### CODE REVIEW

**Comment by nschonni** [comment]
Hmm, that didn't seem to fix it. Can one of the admins try cleaning the Travis cache https://docs.travis-ci.com/user/caching#Clearing-Caches

**Comment by nschonni** [comment]
Nevermind, it's also failing on my fork

**Comment by nschonni** [comment]
OK, the commits are a little messy, but it's building a gain. Let me know if you want a rebase.

**Comment by nschonni** [comment]
@benbalter this should get things mergable again

**Comment by jbjonesjr** [comment]
Thanks @nschonni for looking into this.

**Pull request merged**
