### PR TITLE
The Net Party

### PR DESCRIPTION
**Pull request by rickyrauch**
A week ago I saw you had created Github Goverment and thought it was a unique opportunity to show the developer community what we are building at  http://github.com/democracyos.

### CODE REVIEW

**Comment by nschonni** [comment]
Looks like there is a junk image in there with a space in the name

**Comment by rickyrauch** [comment]
@nschonni Thanks! I fixed it.

**Comment by nschonni** [comment]
No problem, but you should probably put the org under "Civic Hackers" unless it's actually a government organization

**Comment by rickyrauch** [comment]
@nschonni Cool

**Comment by benbalter** [comment]
@gravityonmars Thanks for taking the time to write this up. Such as cool idea.

First, I'd probably break this up into two pull requests, one to add the organization, and another with the post. Would love to get you listed as soon as possible.

Second, have you had a chance to look at the [style guide](http://government.github.com/submit/style-guide/)?  Most notably, would love to shorten things up significantly (even if we have to link elsewhere), and would want it to be written in the third, not first person.

Last, and this could just be a limitation of my understanding of the system, has the application been used in an election? Would love to see if we couldn't tell the story from the government's perspective, the challenges they faced, how they were solved, etc.

Again, awesome story, and looking forward to working with you to tell it.

**Comment by benbalter** [comment]
@gravityonmars any interest in revisiting this?

**Comment by rickyrauch** [comment]
@benbalter I will get it done this weekend :)

**Pull request closed without merging**
