### PR TITLE
Use sub-bullet for note

### PR DESCRIPTION
**Pull request by nschonni**
The generated double paragraph caused an odd gap in the list

### CODE REVIEW

**Comment by nschonni** [comment]
Rebased to remove conflict with #37

**Comment by afeld** [comment]
Mind including a screenshot of the before and after?

**Comment by nschonni** [comment]
OK, but it'll have to be tomorrow :smile: 
You can see the gap above the Git bullet here https://github.com/github/government.github.com#requirements and compare it to the sub-bullet version here https://github.com/nschonni/government.github.com/blob/9ea0640827a32d3d6e204fe59b2e4dfdaba4a430/readme.md#requirements

**Comment by afeld** [comment]
Ah, I see.  In that case, mind just [indenting to four spaces](http://stackoverflow.com/editing-help#advanced-lists)?

**Comment by jlord** [comment]
Sorry we're having such a long discussion about this one line! I'm to blame for its current state, and think I may not have even intended to have any indent, just italics. It's just meant to be an aside, or note about things and not necessarily sub anything. :)

**Comment by jlord** [comment]
Thanks for spotting this @nschonni! I just made it a non-sub level thing, just an italic note.

**Comment by nschonni** [comment]
LOL to landing that then changing it back. You can just say no, my feelings won't be hurt :smile:

**Pull request merged**
