### PR TITLE
Update governments.yml

### PR DESCRIPTION
**Pull request by JSLair**
Hello,

I'm asking you to add the Vitam Program orgnization to this list.
It's an interdepartmental project on digital archiving.

[Short english presentation](https://github.com/ProgrammeVitam/vitam/blob/master_0.15.x/README.en.rst)

Regards

### CODE REVIEW

**Comment by nschonni** [comment]
The build failure is unrelated to your change, I opened #581 to fix it

**Comment by JSLair** [comment]
Do I have anything else to do?

**Comment by jbjonesjr** [comment]
@JSLair nope, this is enough. Really cool project, wonderful work by the :fr: government to collaborate in this fashion.

**Comment by JSLair** [comment]
Thanks a lot

**Pull request merged**
