### PR TITLE
Add an entry for Singapore

### PR DESCRIPTION
**Pull request by jsyeo**
Count us in too!
:raised_hands: :raised_hand:
lol

### CODE REVIEW

**Comment by benbalter** [comment]
I really like the GIF. Quick question: is @moexmen a government agency?

**Comment by jsyeo** [comment]
> is @moexmen a government agency?

Yep. We are a new digital services team in the Ministry of Education, hence the abbreviation moe in the org name. Xmen is simply a code name that's used internally.

**Comment by benbalter** [comment]
Awesome. Thanks @jsyeo!

**Comment by jsyeo** [comment]
Thanks for the merge, @benbalter!

**Pull request merged**
