### PR TITLE
AWS cloud page

### PR DESCRIPTION
**Pull request by sophshep**
This PR recreates https://enterprise.github.com/aws/gov-cloud onto the government.github.com domain. 

👀 [View on staging](https://github-9bd3ab8b29.drafts.github.io/government.github.com/aws-govcloud) 👀 

This is so that as we redirect all marketing pages away from enterprise.github.com, we will have a place to point to (since this content is occasionally still used, as [discussed in Slack here](https://github.slack.com/archives/C0EAHQCB0/p1544055818005600)). More context for why we're removing content from enterprise.github.com [can be found here](https://github.com/github/enterprise-web/issues/5413). 

It keeps the layout similar, but more in line with the rest of the government site.

image

cc/ @jbjonesjr @mdo @msbise @adamahata

### CODE REVIEW

**Comment by jbjonesjr** [comment]
Thx @sophshep!

I'll work in the govt status checks later today/this weekend (that's on me).

**Comment by mdo** [comment]
Nice! Does this need to be linked from the homepage or anywhere else?

**Comment by jbjonesjr** [comment]
The frontpage has an AWS GovCloud call out, probably a great place to link from:

image

We (aka, @github/government or someone in marketing) could also work on creating a new page (based on this template) over the next few weeks and put together some copy for Azure Federal Data Center availability, now that it was made available in GitHub Enterprise 2.15.0 that could be linked alongside this.

**Comment by sophshep** [comment]
@jbjonesjr Good call! I added the link to this page from there.

**Comment by sophshep** [comment]
@jbjonesjr, we'd love to ship this today ahead of GitHub Enterprise redirects that will come tomorrow. Would this be possible?

**Comment by jbjonesjr** [comment]
@sophshep i'm ready to 🚢

**Comment by sophshep** [comment]
@jbjonesjr sweet! CI is still failing. Can you resolve that and merge?

**Review by jbjonesjr — APPROVED** [review]

**Review by elstudio — APPROVED** [review]
Looks fabulous!

**Comment by jbjonesjr** [comment]
admin merging the changes in. 2/3 of the build failures were the aws-cloud-page the PR was adding, and the last was a hiccup in the html-proofer gem.

**Pull request merged**
