### PR TITLE
Fix heroku hyperlink

### PR DESCRIPTION
**Pull request by sebasmagri**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by jlord** [comment]
Thanks @sebasmagri!

**Comment by benbalter** [comment]
Looks like Prose ate the front matter? http://government.github.com/stories/design-a-street-with-streetmix/

**Comment by jlord** [comment]
@benbalter Whaaat?! I saw that it had in the orig PR so then I went in and added it back. I added back, I took all the extra hypens out. I did, I did! Gah.

**Comment by jlord** [comment]
All is well! Was a missing space, fixed here: baa377ce17e6f82e4de14a7df53b83a7ac4ea311

**Pull request merged**
