### PR TITLE
Add count to org list

### PR DESCRIPTION
**Pull request by benbalter**
This is helpful to say, "oh, there are N US Agencies are on GitHub", without needing to count.

Looks a big ugly, but perhaps right aligned, and grey? I dunno. @jlord what do you think?

screen shot 2014-08-01 at 6 34 27 pm

### CODE REVIEW

**Comment by jlord** [comment]
I think adding a count is a great idea!

Playing with the style some, but I'm not sure if this is just crazy:

screen shot 2014-08-03 at 8 02 57 pm

**Comment by benbalter** [comment]
I like it. Perhaps " - N organizations" or " - N orgs"?

**Comment by jlord** [comment]
@benbalter :+1: yep! Just pushed commits:

screen shot 2014-08-04 at 12 46 47 pm

**Comment by benbalter** [comment]
CI is failing due to the `.ruby-version` file. Will take a look. Otherwise, :+1:. 

Thanks, once again, for de-uglifying my code! :smile:

**Pull request merged**
