### PR TITLE
Adding RegioneER government organization

### PR DESCRIPTION
**Pull request by tassoman**
Adding Regione Emilia-Romagna government organization

### CODE REVIEW

**Comment by benbalter** [comment]
Thanks @tassoman our first :it: organization!

**Comment by tassoman** [comment]
I've pushed also PloneGov Italian organization we're promoting inside our country. 
What's wrong with Travis CI build?

**Comment by benbalter** [comment]
Huh. Thought I merged the first commit. Looks like @formezPA is a user, not an organization. Is @formez the proper organization?

Also, I just want to confirm, @PloneGov-IT is publicly funded?

> What's wrong with Travis CI build?

Not your fault, I'll fix on master (listed org is no longer active).

**Comment by tassoman** [comment]
Well, about @formez and @formezPA really I can't say because I'm not directly involved into that organization. Maybe you're right but a deeper investigation by github moderators would be enough to discover about it. In doubt... I could remove this row from the list, no problem.

PloneGov.it is not a formally founded organization but an informal group of local public administrations we promote. @PloneGov-It organization is its open repository

Today we choose this kind of informal promotion and aggregation because of bureaucracy overhead not compatible with open development. If you don't want to list informal organizations, no worries removing this row.

**Comment by FormezPA** [comment]
Hi,
I've created the accounts, but isn't clear for me the subject of the
discussion.
Formez is the organisation, FormezPA a user.

May I help you?

Best regards

Marcello Verona

P.S: In cc my colleague Sabrina Onano, employee at Formez (I'm a
consultant).

2014-09-17 16:57 GMT+02:00 Pierluigi Tassi notifications@github.com:

**Comment by tassoman** [comment]
Ciao Marcello,
 I've suggested adding @Formez organization to https://government.github.com/community in the _Italy_ sublist we're going to add. Please let we know if your organization agrees being listed as described in this pull request.

**Comment by FormezPA** [comment]
Ciao Pierluigi,

I think it's an interesting initiative!

Salvatore, do you agree?

M

2014-09-18 13:44 GMT+02:00 Pierluigi Tassi notifications@github.com:

**Comment by FormezPA** [comment]
We would be pleased to be in the list!
Thank's
S

2014-09-18 14:10 GMT+02:00 Marcello Verona marcelloverona@gmail.com:

**Comment by benbalter** [comment]
> Formez is the organisation, FormezPA a user.

@tassoman looks like it should be @formez, not @formezpa, and then glad to merge. Thanks again!

**Comment by benbalter** [comment]
Thanks @tassoman! :it:

**Comment by tassoman** [comment]
Nice! Grazie tanto!
:+1:

**Pull request merged**
