### PR TITLE
Add CERT-UK to List

### PR DESCRIPTION
**Pull request by zebde**

### CODE REVIEW

**Comment by zebde** [comment]
@benbalter I have removed two dead links but Travis is still failing on an empty page. Could you help?

**Comment by benbalter** [comment]
@cwtaylor looks like we got bit by https://github.com/jekyll/jekyll-redirect-from/pull/111. If you merge in `gh-pages`, tests should now pass.

**Comment by zebde** [comment]
@benbalter Thanks, should be good to merge now.

**Comment by benbalter** [comment]
Thanks @cwtaylor!

**Pull request merged**
