### PR TITLE
Add virtual-world-framework organization to site

### PR DESCRIPTION
**Pull request by jessmartin**
The virtual world framework is being developed for use by the different branches of the armed forces and is funded by the US Office of the Secretary of Defense. See the FAQ page for more info: http://virtualworldframework.com/web/faq.html

### CODE REVIEW

**Comment by afeld** [comment]
While it is cool that they are funding an open-source library like this, I would argue that this GitHub Organization isn't really _about_ government, so much as it's created _by_ government.  As another example, NASA was working on [OpenStack](https://github.com/openstack), but I don't think that's appropriate for this site.

Anyone else have thoughts on this?

**Comment by jessmartin** [comment]
@afeld It's true that [Virtual World Framework](github.com/virtual-world-framework) is not _about_ government, but rather funded _by_ government in order for them to streamline their training and simulation stack across the different branches of the military. I was inspired to add it as I was looking through the other projects already on the list. [Ozone Platform](https://github.com/ozoneplatform), for example, looks like a similar effort to VWF - not _about_ government, but created _by_ government to streamline and standardize - and it also looks really cool! Also, I saw our friends at [ADL](https://github.com/adlnet) on the list, and if you look at their repos, their top repo is a fork of VWF. :smile:

Anyways, I guess I wasn't clear on exactly what the "GitHub and Government" minisite was for. Whatever you guys decide, I'm good with it. It's neat to see all of these government projects organized in one place. Keep pushing open source forward and keep up the great work! :clap:

**Comment by jlord** [comment]
:thumbsup: I'm keen to add it.

The government isn't always going to be able make the technology themselves, they're often going to contract a group to make it. That group may then have a GitHub repo for that specific technology that they are building just for that government entity (and beyond since it's open source). This is very similar to Code for America.

Code for America works more broadly (many cities and projects at once), however, and therefore they're in the Civic Hacker group. If this project is specifically funded by and being built for the US Federal government, I think it's ok to have it listed as it is in this PR. 

As we continue to get the PRs for projects, we're learning the scope and complexity of all these relationships. I imagine there will be these bumps and once things settle down a bit we'll have a better idea of guidelines and structure. And it can always be edited :)

Thanks for taking the time to contribute @jessmartin!

**Comment by benbalter** [comment]
:+1:. This is what did it for me:

> Currently the DoD owns the rights to the source code of the VWF, however as it is licensed using Apache II this means that it is freely usable by any and all as long as original attribution is given to the creators.

If it's a government-finance 501(c)(3) for example, or a government corporation, or if the copyright was being held in the private sector, would be a different story.

p.s. Awesome project, awesome site.

**Comment by afeld** [comment]
@benbalter Think we should move any of those specifics into #74?

**Comment by jessmartin** [comment]
Thanks for the merge guys!

**Pull request merged**
