### PR TITLE
Update Madagascar Gov repository

### PR DESCRIPTION
**Pull request by ugd-mg**
e-Gov Madagascar branch
https://digital.gov.mg

**Your Organization**: _eGouvernance Madagascar_  
**GitHub Organization url**: _@egouvmg_  
**Country/Locality**: _Antananarivo, Madagascar_

### CODE REVIEW

**Comment by mlinksva** [comment]
@egouvmg it appears that @egouvmg ie you 😄 are a user rather than an organization, so there's still a failing test:

> In governments.yml, in the Madagascar group, the following entries are users, not orgs:
>
> egouvmg

Article on how to convert to an organization: https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/converting-a-user-into-an-organization

**Comment by nschonni** [comment]
@mlinksva I think the one to fix and land is https://github.com/github/government.github.com/pull/839, which has the org instead of the user

**Comment by ugd-mg** [comment]
Thank you @mlinksva and @nschonni. I created this organization yesterday @e-Gouvernance-Madagascar. I add it in governments list but still the same error

**Comment by mlinksva** [comment]
@egouvmg it looks like you succeeded in #842. 👍 🇲🇬 I'll merge that. For the future, it's generally better to add commits to an existing pull request to fix  a problem with the pull request rather than to open new ones until you find the right combination. 😄

**Pull request closed without merging**
