### PR TITLE
Fix for #171

### LINKED ISSUE #171: Community grid not displaying correctly
I'm guessing during one of the merges of the updates to the css/bootstrap/whatnots that something got changed that created this bug in the display of orgs on /community:

screen shot 2013-11-04 at 11 52 18 pm

There shouldn't be almost blank rows. It's happening if a type-block ends up in the last position of a row.

Will try and fix it in the morning (it's late here!).

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #171.

### CODE REVIEW

**Comment by benbalter** [comment]
Nice. Are you able to provide a screenshot?

**Comment by benbalter** [comment]
@gjtorikian any idea why tests are failing now? Those URLs definitely are not 404s.

**Comment by XhmikosR** [comment]
Not at the moment because my jekyll installation is broken after upgrading to v1.3.0. Windows and Ruby are a pain in the a**...

**Comment by gjtorikian** [comment]
@benbalter Investigating.

**Comment by XhmikosR** [comment]
Before


---

After

**Comment by benbalter** [comment]
Awesome. Thanks.

Also, @XhmikosR you may want to check out https://github.com/github/pages-gem if you do a lot of work with GitHub Pages.

**Comment by XhmikosR** [comment]
@benbalter: thanks I'll have a look at that gem.

About the Travis errors it's because github returns a 404 when the user isn't logged in and views https://github.com/github/government.github.com/issues/new

PS. Can you merge my other PRs so that I can work on the http requests?

**Comment by gjtorikian** [comment]
> About the Travis errors it's because github returns a 404 when the user isn't logged in and views

Oh wow, yeah. Duh. Thanks for saving me from debugging. :grin: 

Sounds like a list of links to ignore. Is that okay with you, @benbalter?

**Comment by XhmikosR** [comment]
Not only https://github.com/github/government.github.com/issues/new but also https://github.com/new

**Pull request merged**
