### PR TITLE
Move custom redirect.html to a new filename to fix compatibility with jekyll-redirect-from

### PR DESCRIPTION
**Pull request by parkr**
https://github.com/jekyll/jekyll-redirect-from/pull/131 added a layout to our redirect page so folks could customize them.

This created an incompatibility with anyone using both `jekyll-redirect-from` and a custom, unrelated layout called `redirect.html`.

This PR should patch up this site.

/cc @jbjonesjr @benbalter

### CODE REVIEW

**Comment by jbjonesjr** [comment]
Thanks @parkr . I did not know about the custom redirect model, totally explains how we were using this and overriding the core logic. Thanks for the experience to ferret this out.

Anyone ( @benbalter, @parkr have any issues if I :ship:)

**Comment by parkr** [comment]
:shipit:

**Review by benbalter — APPROVED** [review]
:+1: Alternatively, we could kill the custom redirect and just use `jekyll-redirect-from` now that it exists :smile:.

**Comment by parkr** [comment]
> we could kill the custom redirect and just use jekyll-redirect-from now that it exists 😄.

Yeah, though it'd make the process of updating the case study links a little more manual. :shrug:

**Pull request merged**
