### PR TITLE
Adds datauy from Uruguay to organizations.

### PR DESCRIPTION
**Pull request by gabelula**
Website: www.datauy.org

### CODE REVIEW

**Comment by benbalter** [comment]
@gabelula thanks for the pull request. It looks like @datauy is a non-profit, not an official government organization, is that correct? If so, at least for now, I believe it's better suited in the "civic hackers" group.

**Comment by gabelula** [comment]
Yes. Where do I have to add it then?

**Comment by benbalter** [comment]
In the same file, just under the "civic hackers" heading towards the bottom of the file.

**Comment by benbalter** [comment]
Sorry for the delay! Glad to have you added.

**Pull request merged**
