### PR TITLE
Update governments.yml

### PR DESCRIPTION
**Pull request by gunzip**
Added AgID to the list - https://github.com/AgIDgov

### CODE REVIEW

**Comment by jbjonesjr** [comment]
Hey @gunzip. I don't have access to your fork to make changes, so can't update your branch. if you want to do that (and keep an eye on it as other people may beat you to it), i'll merge your change. looks good to me.

**Comment by gunzip** [comment]
Done, but it seems that there are some unrelated errors on travis-ci. It's ok for me to merge.

**Comment by jbjonesjr** [comment]
@gunzip yep, there was an upstream coffeescript/jekyll issues earlier that got us. I patched it in #515 , and am good to go. If you want to update your branch again, I can give it a merge.

NOTE: In the future, PRs from forks now have an option to allow collaborators to contribute. That would allow me to do the fast-forward merge myself and save trouble. Keep it in mind!

**Comment by gunzip** [comment]
gotcha.

**Pull request merged**
