### PR TITLE
Break up Civic Hackers, Script CFA Updating

### PR DESCRIPTION
**Pull request by benbalter**
This pull request
1. Breaks up the long list of "Civic Hackers" with groups for Code for America and Open Knowledge Foundation
2. Adds a small `script/fetch-cfa` to update the list of known brigade orgs via the CfA API

Questions:
1. Any other large groupings worth breaking up?
2. Are these all the brigades? Are we using the API properly?

/cc @ashleymmeyers for the excellent idea (and @jlord because CFA :smile:)

### CODE REVIEW

**Comment by benbalter** [comment]
What it looks like in action:

screen shot 2014-06-11 at 2 16 24 pm

**Comment by benbalter** [comment]
@nickstenning looks like you're the maintainer of okfn.org? is there any way to programmatically retrieve a list of OKFN chapters?

**Comment by ashleymmeyers** [comment]
@ondrae Built our API and can help. Ben does this revised list now mean we can build a GH Page with all our orgs (brigades, startups, Fellows, etc.) pulled in?

**Comment by jlord** [comment]
Cool, cool!

**Comment by nickstenning** [comment]
@benbalter Yes there is! All groups:

```
curl -sSL https://okfn.org/network/csv
```

Only chapters (officially-sanctioned entities):

```
curl -sSL https://okfn.org/network/csv | csvgrep -c 'Local Groups status' -m Chapter
```

I guess we should probably add GitHub username to the groups.

**Comment by benbalter** [comment]
@nickstenning Thanks! Not a priority, but if it's possible to add GitHub username to that CSV output, would love to script keeping this up to date so we can ensure all the chapters are included. :smile:

**Pull request merged**
