### PR TITLE
added baltimorecounty to the mix

### PR DESCRIPTION
**Pull request by talllguy**

### CODE REVIEW

**Comment by nschonni** [comment]
Looks like a few extra commits snuck in there :wink:

**Comment by talllguy** [comment]
@nschonni I saw that and am confused. How did that occur?

**Comment by nschonni** [comment]
I think you created your branch off of the "accessibility" branch instead of the "gh-pages" one. The accessibility branch hasn't been merged in, so its commits were included.

**Comment by talllguy** [comment]
@nschonni ah, n00b error on my part. What should I do now?

**Comment by nschonni** [comment]
I'd close this and create a new branch off of `gh-pages`

**Pull request closed without merging**
