### PR TITLE
added OpenProcure.us

### PR DESCRIPTION
**Pull request by alan707**
added https://github.com/munirent/openprocure to the list.  Hopefully it was in the appropriate place.

### CODE REVIEW

**Comment by jbjonesjr** [comment]
@alan707 close... This file lists organizations, not specific repos.  It looks like the `munirent` org has  a ton of stuff in it that may not be really relevant, so it might make more sense to start up a new org to house the openprocure specific stuff. Up to you. 

Update the PR as appropiate.

**Comment by alan707** [comment]
got it, thx. So there is no specific place to add standalone repos?

**Comment by jbjonesjr** [comment]
@alan707, nope, just `Organizations` (in the GitHub sense at least).

**Comment by alan707** [comment]
ok, I'm closing this PR then.  Thanks for the explanation!

**Pull request closed without merging**
