### PR TITLE
Added rOpenGov to _config.yml

### PR DESCRIPTION
**Pull request by ouzor**
Added organization rOpenGov to _config.yml

### CODE REVIEW

**Comment by jlord** [comment]
Awesome, thank you @ouzor!

**Comment by ouzor** [comment]
Excellent, thanks!

br, Juuso

**Comment by benbalter** [comment]
@jlord is `international` an extension of `civic hackers`? Neither this nor ogpl appear to be government organizations.

**Comment by nschonni** [comment]
OGPL is a cross government initiative and that's why I added it under international :wink:

> The Open Government Platform (OGPL) is a product developed by the governments of India, Canada, and the United States to promote transparency and greater citizen engagement by making more government data, documents, tools, and processes publicly available through a freely available, open source platform.

**Comment by ouzor** [comment]
Hi!

Yes it was not exactly clear whether rOpenGov should be under International
or civic hackers. This is indeed a civic hacking project so maybe I should
move it there. Or you can do it as well, that's fine with me!

br, Juuso

**Pull request merged**
