### PR TITLE
Add Dept of Digital Fabrication - São Paulo, Brazil

### PR DESCRIPTION
**Pull request by has256**
FAB LAB LIVRE SP (https://github.com/fablablivresp/) is the repository for the Department of Digital Fabrication from São Paulo, SP, Brazil - http://fablablivresp.art.br/. 

We are the maintainers of the first brazilian experience of public policy based in digital fabrication laboratories.

---

Thanks for the contribution! **Below** is a template that can make it easier when submitting your Organization:

**Your Organization**: _Dept. of Digital Fabrication (DFD/CCD/SMIT/PMSP)_  
**GitHub Organization url**: _@fablablivresp_  
**Country/Locality**: _São Paulo, SP, Brazil_

Inclusion requirements:
- [X] Referenced account is an [Organization](https://github.com/github/government.github.com#add-organization) not a User^
- [X] If this is a government project, your Organization's description should include a reference to your country/agency.
- [X] Make sure your Organization includes at least one public repository
- [ ] Please also include a URL for your organization that links back to your organization or agency homepage.
 
^ If you want to convert your account to an org, details can be found here: https://help.github.com/articles/converting-a-user-into-an-organization/
  
 :heart: GitHub Government Contributors

### CODE REVIEW

**Comment by jbjonesjr** [comment]
@el-cardu 👏 This looks good, I just need you to update your branch to be aligned with the head, and we can go ahead and get this merged. Since you didn't give admin's privileges to update it, I can't do the update myself. Ping me once you have done that, and i'll merge.

**Comment by has256** [comment]
Oh, @jbjonesjr, thank you very much by the answer and by your kindness! :tada: 

I was following this guidelines (https://government.github.com/community/), so I made this PR by Github Interface (not by CLI) and I think that I delete by accident my fork (:-1: sorry!). 

So, since I don't find by interface any button to link this PR with other repo (git/github newbie here, :laughing:), I think that's better open a new PR and close this one. Can I follow with that? Any other suggestion?

Thx again!

**Comment by jbjonesjr** [comment]
@el-cardu Opening and closing is fine if you want to do it again. To save you that trouble, i'll go ahead and make the merge for you myself. I think because you deleted the fork after submitting is why I can't make the update now.  Good thing is GitHub never forgets :)

**Comment by jbjonesjr** [comment]
Closing as this was merged upstream.

**Pull request closed without merging**
