### PR TITLE
Added navikt organization under Norway

### PR DESCRIPTION
**Pull request by jhrv**
GitHub-govt. organization 'navikt' is the IT-department for the Norwegian labour and welfare administration

### CODE REVIEW

**Comment by benbalter** [comment]
Thanks @jhrv!

**Comment by jhrv** [comment]
Thanks @benbalter :)

**Comment by matsbyfl** [comment]
Hi,

Just wanted to say hello and wish you a good day! By the way, have you seen that  http://xyshantuche.midgetpettingzoo.com/aeyan

Best Wishes, mats@byfuglien.net

**Comment by matsbyfl** [comment]
Greetings! 

I wanted to  share  with you something  important , I guess I really  and truly am  in love this time! Take a look  at some pics of us http://demand.johnleepictures.us/aebnrc

Rushing, mats

**Comment by matsbyfl** [comment]
Yo! 
I was  reading  an article  and suddenly came  accross those  words, they  are just perfect, you can find  the article here http://result.colourbynumbers.com/aeckerf
My best to you, mats

**Pull request merged**
