### PR TITLE
Cleanup orgs for the build to pass

### PR DESCRIPTION
**Pull request by nschonni**
Org appears to be deleted and is failing the build now

### CODE REVIEW

**Comment by nschonni** [comment]
Build is now green again

**Comment by jbjonesjr** [comment]
Figured out they are now "mapseed". Not sure if they are still C4A affiliated, so just put it in civic hackers section.

Thanks for chasing this down @nschonni

**Comment by jbjonesjr** [comment]
more failures!!! why is life so hard? I'll mess with this in a bit

**Comment by jbjonesjr** [comment]
Looks like someone destroyed the Canadian org (GoC) and PWGSC got moved to `pspc-spac`

**Pull request merged**
