### PR TITLE
NCIP Post - Opening up informatics for cancer research

### PR DESCRIPTION
**Pull request by klemmj**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by benbalter** [comment]
@klemmj This is amazing, and such a great story to be told. I did not know about http://ncip.github.io/, and hope that we can help to inspire others with these great efforts. Two small notes, but otherwise would love to see about merging this in this week.
1. We usually use the term "Organization" or "Organization Page" to describe the presence at [github.com/ncip](https://github.com/ncip) rather than "Channel". Very minor, but wouldn't want to confuse readers that it may be a different form of agency presence on GitHub. To make any subsequent changes, you can do so via prose, or by simply clicking "edit" on [this page](https://github.com/klemmj/government.github.com/blob/prose-patch-1/_posts/2013-11-20-opening-up-informatics-for-cancer-research.md). Changes made there will be reflected in this pull request automatically.
2. You'll notice the other stories on [government.github.com](http://government.github.com/) have images associated with them. Is there an image that you think would accompany the story well? If so, if you simply drag and drop the image into the comment box on this page, we can add it to the post.

//cc @arfon because science.

**Comment by klemmj** [comment]
nih-imagebank-1273-300
This is an image of human prostate cells, used in the study of cancer.  Will this work?  It is in the public domain, through the NIH image bank.

**Comment by arfon** [comment]
Thanks for brining me in on this thread @benbalter. This is such a great story and it's awesome to see it going up on the government site.

**Comment by klemmj** [comment]
Thanks for the quick turn around and helping us get the word out!

**Comment by benbalter** [comment]
The story is [on the homepage](http://government.github.com), and can be linked to directly as [government.github.com/stories/opening-up-informatics-for-cancer-research](http://government.github.com/stories/opening-up-informatics-for-cancer-research/).

Thanks for taking the time to tell your story, and for the quick fixes. WIll definitely be sending some other government agencies this way and to http://ncip.github.io/ very soon. :smile:

**Pull request merged**
