### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by benbalter** [comment]
@XhmikosR as much as possible, granular pull requests would be greatly appreciated and much easier to review / accept. :smile:

**Comment by XhmikosR** [comment]
I know, I know... But it's easier this way for me since most changes I do them along the way and aren't planned.

I'll try to split the patches later, but it would help me if I didn't :)

**Comment by XhmikosR** [comment]
Can we get this in? My [requests](https://github.com/XhmikosR/government.github.com/tree/requests) branch conflicts with these changes.

**Comment by XhmikosR** [comment]
@benbalter: can't you merge this one as it is?

**Pull request closed without merging**
