### PR TITLE
Adding dxw

### PR DESCRIPTION
**Pull request by lilydartdev**
Adding dxw to UK organisations. 

We work within central government and the public sector. Our partners include: Department for Communities and Local Government, Government Digital Service, Ministry of Justice, Department for the Environment, Food and Rural Affairs, London Borough of Camden Council, Department of Health and Public Health England.

### CODE REVIEW

**Comment by jlord** [comment]
Thanks for helping make the list better @lilydart-dxw! Right now the orgs listed under countries are the GitHub accounts belonging to the governmental body itself. 

If I'm understanding correctly, you're a consultancy who works with the governmental bodies (which is a model I love!) so while not ideal, the Civic Hackers section may be the best fit right now.

**Comment by lilydartdev** [comment]
Hi Jessica

I saw a couple of other (what looked liked) agencies like Code for Europe and Team POPONG on the list so I thought it was not just government organisations, have I gotten the wrong end of the stick?

Thanks

Lily

---

Lily Dart (@lily_dart)

http://dxw.com/
Phone: 0345 257 7520
Mobile: 0772 573 2433

On 18 December 2013 at 19:35:58, Jessica Lord (notifications@github.com) wrote:

Thanks for helping make the list better @lilydart-dxw! Right now the orgs listed under countries are the GitHub accounts belonging to the governmental body itself.

If I'm understanding correctly, you're a consultancy who works with the governmental bodies (which is a model I love!) so while not ideal, the Civic Hackers section may be the best fit right now.

**Comment by jlord** [comment]
Nope, you're right they're on the list and we want you on the list too for sure! It's just a matter of putting y'all in the right category like how Code for Europe is under 'Civic Hackers'. So if you want to edit the list again and move your group to the Civic Hackers list that would be awesome!

**Comment by lilydartdev** [comment]
Edited, thanks!

**Comment by jlord** [comment]
Oddly, there were some files here that are a part of an unmerged PR #207 so I manually removed them and merged the changes to organizations.yml.

**Pull request merged**
