### PR TITLE
Add iSC OpenData

### PR DESCRIPTION
**Pull request by suriyaa**
Hi, :smile:

I added **iSC OpenData**.
## About

**iSC OpenData** _is a non-profit organisation which belongs to iSC Group which is focused on government and Open Knowledge._

Yours,
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

### CODE REVIEW

**Comment by nschonni** [comment]
Is it actually a member of https://okfn.org/? Otherwise maybe it would be better under civic hackers

**Comment by suriyaa** [comment]
It's under **Open Knowlege**. :smile:

Yours,
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by nschonni** [comment]
Yeah, my question was should it really be under Open Knowledge Foundation, because that is a legal entity and the orgs under there are their actual branches (like Code for America)

**Comment by suriyaa** [comment]
Hi again, :smiley:

well **(iSC) OpenData** is a non-profit organization and a institute which belongs to _iSC Group_ and people who interest on _Open Knowledge_.

However **OpenData** is mostly focused on _Open Knowledge_ :+1: than _Civic Hackers_.

And I'm sure it it comes under "_Open Knowledge Foundation_".

[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by benbalter** [comment]
@SuriyaaKudoIsc Open Knowledge Foundation (https://okfn.org/) is a specific organization (like Code For America), with local, officially sanctioned chapters.

Can you tell us a little more about (iSC) OpenData? Does it have a website? Looking at the organization page, other than a few forks, there's not too much to explain the organization.

**Comment by suriyaa** [comment]
@benbalter: Sorry for the late answer. I did not have much time to answer your question.
Well here it is:

## About it/us

**[OpenData](https://github.com/iSC-OpenData)** is a new started project organisation by _[iSC Group](https://github.com/iSCGroup)_, an enterprise group.

## Name

_OpenData_ It is also called _iSC OpenData_. We often short it to _OpenData_. So "_iSC_" does not have to be necessarily added.

## Destination

_OpenData_ focused mostly on _Open Knowledge_ and worked together with them. :+1:
_OpenData_ is also focused on _government_.

## Community

Actually it have over _20 members_ over the world (_USA, Canada, Germany and Australia_). It is supported by us. :smile:

## Website

As I said we're a new organization that just created the website. :wrench:

Find the fork repo [here](https://github.com/iSC-OpenData/isc-opendata.github.io) and the orginal repo [here](https://github.com/iSC-Host/opendata.isc).

## More information

Do you need more or another informations ask me please.

Yours,
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by suriyaa** [comment]
iSC OpenData is now a dissolved organization.

**Pull request closed without merging**
