### PR TITLE
Update _config.yml

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Portail open data de la Ville de Montpellier

**Comment by benbalter** [comment]
is @ VilleDeMontpellier a company or a government entity?

Also, it looks like it's a user, not an organization. Perhaps you'd consider [converting to an organization](https://help.github.com/articles/converting-a-user-into-an-organization), before we add it?

**Comment by ghost** [comment]
The city of Montpellier is an organization, it is a French city of 250,000
residents.

2013/10/16 Ben Balter notifications@github.com

> is @ VilleDeMontpellier a company or a government entity?
> 
> Also, it looks like it's a user, not an organization. Perhaps you'd
> consider converting to an organizationhttps://help.github.com/articles/converting-a-user-into-an-organization,
> before we add it?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/github/government.github.com/pull/51#issuecomment-26444345
> .

## 

Cordialement

Valentin Jérémie, Docteur en géographie
Chef de projet OpenData Ville de Montpellier
http://opendata.montpelliernumerique.fr/
06.20.32.00.24
Montpellier III, ART-Dev, UMR 5281 CNRS

**Comment by jlord** [comment]
Thanks @VilleDeMontpellier! We just try to double check emails to verify when an account is official versus created by a community group. But the city's [website](http://opendata.montpelliernumerique.fr/Le-depot-GitHub) links to this GitHub account :thumbsup: 

+1 to @benbalter's thought - you may want to switch it over to an organization so that you can have other people in your organization contribute more easily. 

Merci :)

**Pull request merged**
