### PR TITLE
add California Department of Justice

### PR DESCRIPTION
**Pull request by afeld**
https://caldoj.github.io/opii/

### CODE REVIEW

**Comment by jbjonesjr** [comment]
Hey @afeld . @caldoj is a user, not an org, so they won't work. If they want to convert their account to an org, then they can be included. Details can be found here: https://help.github.com/articles/converting-a-user-into-an-organization/

(I'm assuming you have contact with that office and can pass this along?)

**Comment by afeld** [comment]
@rscharfstein Thoughts about converting @caldoj to an organization?

https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by rscharfstein** [comment]
That's a great idea. I'm new to github so appreciate the tip!

**Comment by jbjonesjr** [comment]
Hey @rscharfstein, since this is still failing to build, i'm going to go ahead and close out this issue. If you want to go ahead and convert the account to a Free Organization account, you can reopen the PR and the build should pass.

Thanks, let me know if I can help anyway.

**Pull request closed without merging**
