### PR TITLE
Added City of Denver

### PR DESCRIPTION
**Pull request by schnuerle**
Thanks for the contribution! **Below** is a template that can make it easier when submitting your Organization:

**Your Organization**: _ACME Agency_  
**GitHub Organization url**: _@acmeagency_  
**Country/Locality**: _Alberta, Canada_

Inclusion requirements:
- [ ] Referenced account is an [Organization](https://github.com/github/government.github.com#add-organization) not a User^
- [ ] If this is a government project, your Organization's description should include a reference to your country/agency.
- [ ] Make sure your Organization includes at least one public repository
- [ ] Please also include a URL for your organization that links back to your organization or agency homepage.
 
^ If you want to convert your account to an org, details can be found here: https://help.github.com/articles/converting-a-user-into-an-organization/
  
 :heart: GitHub Government Contributors

### CODE REVIEW

**Comment by jbjonesjr** [comment]
weird the build died...

**Comment by jbjonesjr** [comment]
Hey @schnuerle , it looks like this is a user account not an organization.  As per the Government Best Practices, we suggest they be an [Organization, not a user's account](https://government.github.io/best-practices/account-management/#organization-or-user). If you want to convert your account to an org, details can be found here: https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by schnuerle** [comment]
I am not in charge of this account, I'm in Louisville, KY.  But I saw that it needed to be added.  @CityofDenver should be the one to make the change.

**Comment by jbjonesjr** [comment]
👍thanks @schnuerle .

**Comment by jbjonesjr** [comment]
Since CityOfDenver is still not a valid org (currently a user account), i'm closing this down. feel free to reopen it at a later point if this changes.

**Comment by ghost** [comment]
Hi, could I please get a bit more info on what’s needed to properly set up a government org account?

Thanks,
Matthew


[cid:image002.png@01D34CAD.858D27B0]

Matthew McAllister | Smart City Project Manager
City and County of Denver
p: (303) 956-0100
matthew.mcallister@denvergov.org<mailto:matthew.mcallister@denvergov.org>

**Comment by jbjonesjr** [comment]
Hey @CityofDenver , nothing special about a Government account, just that we require you to be an `Organization` on GitHub.com, and not a `user` account (users are for hooomans, orgs are for groups or 🏛 ).

Details on making the change are here: https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by ghost** [comment]
Thanks, will investigate that. Are the actions your taking today having any impact on the repos we have under the CityofDenver account?

**Comment by jbjonesjr** [comment]
@CityofDenver absolutely not. we just aren't mentioning City of Denver on this website.

**Pull request closed without merging**
