### PR TITLE
Adds dataviz.

### PR DESCRIPTION
**Pull request by ltartari**
Group of open data hackers from Brazil \m/

### CODE REVIEW

**Comment by benbalter** [comment]
It looks like @dataviz is a private company, not a government entity. Perhaps it'd fit better under "civic hackers"?

**Comment by ltartari** [comment]
True that, @benbalter! I will fix it and resubmit. Cheers!

**Comment by ltartari** [comment]
as-nothing-happened
Done, @benbalter!

**Comment by benbalter** [comment]
Awesome. Glad to have @dataviz added to the list. :beers:

**Pull request merged**
