### PR TITLE
Fixes sorting

### PR DESCRIPTION
**Pull request by leucos**
Some countries were not properly sorted. 
Moved E.U. to the bottom, near non-country organizations

### CODE REVIEW

**Comment by jlord** [comment]
Nice, thanks @leucos!

**Comment by benbalter** [comment]
Are we sure that an alphabetical country listing is the right way to go here? Visually, it's a lot less stunning because many of the A's only have one or two accounts:

screen shot 2013-10-21 at 12 55 14 pm

screen shot 2013-10-21 at 12 57 04 pm

/cc #75

**Comment by leucos** [comment]
Mmmh, yes that's a point. It could be nicer (and more interesting) to move up entries depending on how many organization they contain ?

**Comment by nschonni** [comment]
@benbalter the flip to that is that it now highlights that (at least) 13 countries that have repos on the page load instead of the 5 when the US block is first

**Pull request merged**
