### PR TITLE
Add the ability to see organizations in list form

### PR DESCRIPTION
**Pull request by rmw**
It was difficult to know what organizations were based only on their
avatar.  It was also difficult to understand the organization of the
organizations/countries in block format.  While imperfect, showing a
list with a github handle can give more information.
- Add toggle links for list/avatar view
- Add div with list to the community page
- Add id to the community avatar block
- Add styles for org list
- Add a small amount of javascript to show/hide the divs

### CODE REVIEW

**Comment by jlord** [comment]
It is hard to read with just the avatars, and while the avatars make for a nice open-gov-quilt, if someone wants to read them, a list would be more useful. Thanks for getting on this @rmw!

I made a [branch](https://github.com/github/government.github.com/tree/rmw-add-org-list) with your changes and made a few style edits. Here are screenshots so others can get a sense of the updates: 

_list view_
screen shot 2014-01-18 at 5 13 25 pm

---

_avatar view_
screen shot 2014-01-18 at 5 13 15 pm

This list does get really, really, really long and I think it could actually do for some real table formatting so people can sort and such. But I'm :+1: for this in the meantime.

_also_

I did try to have the avatars spill right so that over all the list was shorter and we could fill some of that white space, but because the names vary so much, it was pretty wonky:

screen shot 2014-01-18 at 5 19 37 pm

cc @benbalter

**Comment by rmw** [comment]
Thank @jlord - looks great! I did my best to stay with the styles but happy to have another hand in on that.  Yea, it's unfortunate about the white space, but it's not horrible.  Similar reason I added the border/shadow (empty logos + right align looked weird.)

**Comment by nschonni** [comment]
Removing the "github/" from the names would also thin down the grid

**Comment by jlord** [comment]
@nschonni I added 'github/' because I think it helps identify them as user/org/account names, otherwise, it can look a bit alphabet soup because not all of the account names are very readable. Some of them, even without the 'github/' on the front are still longer than the images ('department-of-veteran-affairs'), so we'd still have the problem even without that prefix :/

**Comment by nschonni** [comment]
For sure, unless you want to loop back to this idea https://github.com/github/government.github.com/issues/54#issuecomment-26468283

> it can look a bit alphabet soup 

Welcome to the government :wink:

**Comment by benbalter** [comment]
>  I added 'github/' because I think it helps identify them as user/org/account names, 

Perhaps @? Would love to keep a grid-ish view for my OCD-ness. :smile:

**Comment by jlord** [comment]
:+1: @benbalter I took out the 'github/'

Since some of the org names are still pretty long, not all of it aligns perfectly, but for the most part, it does the job:

_meh_
screen shot 2014-01-29 at 11 19 32 am

_better_
screen shot 2014-01-29 at 11 19 20 am

Overall though it's definitely much more readable.

**Comment by benbalter** [comment]
@jlord are you still working in the [`rmw-add-org-list` branch](https://github.com/github/government.github.com/tree/rmw-add-org-list)?

**Comment by jlord** [comment]
@benbalter do you mean is that where these updates are? Yep.

**Comment by benbalter** [comment]
Oh man. This is great. Two questions:

> Add toggle links for list/avatar view

What's the value in the toggle? Right, if the original  problem was that "It was difficult to know what organizations were based only on their avatar", why don't we just :fire: the view that's difficult to use? (or is there a legitimate use case for both?) I'm just a big fan of not making options when a decision can suffice. It's just not super-intuitive to me because the initial load state almost looks like a list to me, and the post "view list" link (which has a "view avatars" toggle), contains avatars.

Second, this may break some unspoken CSS rule, but if the content area is 576px, can we just split that in four and have each row contain four equally spaced squares, content centered? (with some not having any content) I think that'd would allow everything to line up.

**Comment by benbalter** [comment]
@rmw or @jlord any interest in picking this up?

**Comment by jlord** [comment]
I made another branch the other day! https://github.com/github/government.github.com/tree/listview, it's very basic but I'll get a PR going :soon:

**Comment by benbalter** [comment]
Closing in favor of #284, but far from finalized. Would still love your help making that page :sparkles:!

**Pull request closed without merging**
