### PR TITLE
Fix the build

### PR DESCRIPTION
**Pull request by ClaudiuCeia**
Two entries in `governments.yml` are users, not orgs so the build is momentarily broken. This PR fixes the issue.

### CODE REVIEW

**Comment by nschonni** [comment]
👍  I left comments on #480 and #457 just now too

**Comment by ClaudiuCeia** [comment]
@nschonni Do you need more info from me on this PR or the one where I'm adding GovITHub? How often do you merge these PRs / push to production?

Thanks

**Comment by nschonni** [comment]
@ClaudiuCeia sorry, I don't have commit rights to the repo. I just try to fix it like you when stuff gets broken

**Comment by ClaudiuCeia** [comment]
Gotcha @nschonni 👍 

Thanks @jbjonesjr!

**Pull request merged**
