### PR TITLE
add Mayor's Office of Data & Analytics

### PR DESCRIPTION
**Pull request by afeld**
https://github.com/MODA-NYC

### CODE REVIEW

**Comment by jbjonesjr** [comment]
thanks @afeld

**Comment by jbjonesjr** [comment]
opps, I spoke too soon. Looks like this is a user account not an organization.  As per the Government Best Practices, we suggest they be an [Organization, not a user's account](https://government.github.io/best-practices/account-management/#organization-or-user). If you want to convert your account to an org, details can be found here: https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by afeld** [comment]
I've nudged them about it. That's a blocker to including it in the list?

**Comment by jbjonesjr** [comment]
@afeld unfortunately, it is. it breaks the build, etc.

**Comment by jbjonesjr** [comment]
@afeld closing this out for the time being. feel free to reopen it if the acct gets squared away.

**Pull request closed without merging**
