### PR TITLE
Update _config.yml with the City of St. Louis, MO

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jlord** [comment]
Thanks @makerops! When I visit: https://github.com/CityOfStLouis, though, it doesn't find the account. Is there a typo?

**Comment by ghost** [comment]
No, no typo.  Does it have to be an official, sanctioned by the city
account?  Or can I create one, and start compiling the resources I have for
St Louis?

**Comment by jlord** [comment]
Well definitely can't add it until the account exists :) But if it's official from the city we'll add it to the US City group, if it's done by you, we'd put it in the Civic Hacker category. Both awesome!

**Comment by afeld** [comment]
@makerops Feel free to re-open (w/ a [rebase](https://help.github.com/articles/interactive-rebase)) when you get that going! :+1:

**Pull request closed without merging**
