### PR TITLE
Update _config.yml

### PR DESCRIPTION
**Pull request by okfngr**
Open Knowledge Foundation Greece

### CODE REVIEW

**Comment by jlord** [comment]
Thanks @okfngr! Did you mean to add the account you submitted the pull request from,`okfngr`? The name you added, `okfn-Greece`, does not appear to be an actual account.

**Comment by okfngr** [comment]
Yes okfngr is fine. However okfngr is the same of okfn-Greece 

Thanks!

Από το iPad μου

18 Οκτ 2013, 4:05 π.μ., ο/η Jessica Lord notifications@github.com έγραψε:

**Comment by dr0i** [comment]
I think it is up to you to fix the name in `_config.yml`. (I had the same problem. The point is, you have to insert the _github_ account name of your organisation).

**Comment by okfngr** [comment]
Thanks @dr0i.
In the new Update_config.yml there is our github account of OKFN Greece @okfngr . (2 days ago)

**Comment by jlord** [comment]
Thanks @okfngr!

**Pull request merged**
