### PR TITLE
add U.S. Department of Transportation Intelligent Transportation Systems Operational Data Environment

### PR DESCRIPTION
**Pull request by afeld**
**Organization**: US Department of Transportation (USDOT) Intelligent Transportation Systems Operational Data Environment (ITS ODE)
**GitHub Organization url**: @usdot-jpo-ode
**Country/Locality**: USA (not sure where specifically)

Inclusion requirements:
- [x] Referenced account is an [Organization](https://github.com/github/government.github.com#add-organization) not a User^
- [x] If this is a government project, your Organization's description should include a reference to your country/agency.
- [x] Make sure your Organization includes at least one public repository
- [x] Please also include a URL for your organization that links back to your organization or agency homepage.

@arielsgold @mvs5465 @hmusavi This pull request is adding your GitHub organization to the list at https://government.github.com/community/. Not sure who the admins are, so reaching out to you since I see you involved with the organization; would you be open/able to update the name+description+URL of the organization in [the settings](https://github.com/organizations/usdot-jpo-ode/settings/profile)?

### CODE REVIEW

**Comment by afeld** [comment]
Build failure seems unrelated to this change.

**Review by hmusavi — APPROVED** [review]
Added inclusion requirements to @usdot-jpo-ode organization as requested
- [X] Referenced account is an Organization not a User^
- [X] If this is a government project, your Organization's description should include a reference to your country/agency.
- [X] Make sure your Organization includes at least one public repository
- [X] Please also include a URL for your organization that links back to your organization or agency homepage.

If there is still any missing information, please let me know.

**Comment by afeld** [comment]
Nice, thanks for the quick turnaround!

**Comment by jbjonesjr** [comment]
thanks for the info @afeld and @hmusavi . Excited to see more DOT projects.

**Pull request merged**
