### PR TITLE
Adding a lot of Norwegian and Swedish agencies

### PR DESCRIPTION
**Pull request by PierreMesure**
Here are some more Norwegian and Swedish agencies along with a few Danish and one Polish. All of them are confirmed government bodies or entities inside of gov bodies.

However, a few of them are research agencies, universities or museums. I was thinking of adding them in the separate research file but I wasn't sure. What's the best way to do it?

### CODE REVIEW

**Comment by PierreMesure** [comment]
Hey, this site has been mentioned at a public sector conference in Sweden and is likely to be used more by Swedish public servants to learn which colleagues to talk with about sharing code. Should we have a discussion on the additions from this PR so it can be merged soon?

**Comment by jbjonesjr** [comment]
@PierreMesure thanks for this addition. for the time being, can you remove the universities? Research agencies and labs are okay, but we've historically not included universities (even if centrally funded). Longer term, they would fall into a separate education section, not the government list.

The rest look goods.

**Comment by PierreMesure** [comment]
There you go! I guess the unis will stay in the history of that PR until we decide to add them somewhere.

**Comment by PierreMesure** [comment]
@jbjonesjr Hey Jamie, any news about when you are going to merge this PR?

A public sector network organisation in Sweden would like to ask gov agencies to list themselves on your website but it would make more sense to do it after you have merged this PR and caught up with the others. Otherwise, you will just have a lot of duplicates and everyone will waste time.

I don't want to stress you though.

**Comment by jbjonesjr** [comment]
Merging in after today's prep work. Thanks for removing the universities, and providing such a large list of orgs.

**Comment by PierreMesure** [comment]
Thanks a lot for taking the time to merge @jbjonesjr, I guess you must have a lot of other things on your plate.

**Pull request merged**
