### PR TITLE
Fix a11y skipped headers and missing link text

### PR DESCRIPTION
**Pull request by dgading**
From the conversation [here](https://github.com/github/government.github.com/issues/583), this PR does the following:

On the homepage updates the **h3**'s to **h2**'s while maintaining their classes for styling. 

On Accessibility switching section headers to **h2**'s instead of an **h3**

On Community removing the **h6** from the no matches, as it's not really a header for a section. Setting the **h3**'s to **h2**'s and their sub heading from an **h4** to **h3**. 

Also on Community, I also removed the **h4** around the input as it wasn't a header, replacing it with a div and a screen reader only label. 

Across the site, in the Footer I updated the octocat link to have a screen reader only "Back to Home" text to address missing text in the link. Since the svgs are loaded through a node module, I couldn't apply a title to the svg and reference it with aria-labelledby.

One thing I didn't fix was the contrast issue on the accessibility page. In the tables, Wave is reporting the text may not meet contrast requirements, but a purely technical fix took away from design aesthetics, so I decided not to attempt them without some direction.

### CODE REVIEW

**Review by nschonni — APPROVED** [review]

**Comment by jbjonesjr** [comment]
Hey @sophshep , as the last one to touch the site design, you :+1: on these changes? Want to make sure these don't cause design system impacts in the future.

**Review by sophshep — APPROVED** [review]
👍  All good from me!

**Comment by dgading** [comment]
I took a look at the details, but wasn't sure what specifically failed. If there something I can take a look at please let me know.

**Comment by nschonni** [comment]
@dgading you just need to merge in the latest changes from gh-pages. The build failures are unrelated to your changes

**Pull request merged**
