### PR TITLE
Add ZJUSCT

### PR DESCRIPTION
**Pull request by psjnek**
**Your Organization**: _ZJUSCT_  
**GitHub Organization url**: _@ZJUSCT_  
**Country/Locality**: _Zhejiang, China_
**Link**: _https://www.zjusct.io/_

Inclusion requirements:
- [x] Referenced account is an [Organization](https://github.com/github/government.github.com#add-organization) not a User^
- [x] If this is a government project, your Organization's description should include a reference to your country/agency.
- [x] Make sure your Organization includes at least one public repository
- [x] Please also include a URL for your organization that links back to your organization or agency homepage.
  
 :heart: GitHub Government Contributors

### CODE REVIEW

**Comment by mlinksva** [comment]
@WebSnke do you see a "resolve conflicts" button like this?

Screen Shot 2023-01-22 at 9 18 08 AM

This usually occurs when git can't tell if a line should be added or replaced. In this repo almost always added, as in this PR. If you can resolve the conflict that would be helpful. See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

**Comment by psjnek** [comment]
> @WebSnke do you see a "resolve conflicts" button like this?
> 
> Screen Shot 2023-01-22 at 9 18 08 AM
> 
> This usually occurs when git can't tell if a line should be added or replaced. In this repo almost always added, as in this PR. If you can resolve the conflict that would be helpful. See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

Thanks, I just resolved the issue.

**Comment by mlinksva** [comment]
Thanks. Some of your other unmerged PRs also have conflicts.

**Comment by psjnek** [comment]
> Thanks. Some of your other unmerged PRs also have conflicts.

Thanks, I just resolved all of them.

**Pull request merged**
