### PR TITLE
Use GitHub release page instead of the Wiki

### PR DESCRIPTION
**Pull request by nschonni**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by nschonni** [comment]
Not sure why the metadata got wiped. Time for a rebase :smile:

**Comment by nschonni** [comment]
Fixed the metadata issue. I don't think prose likes me :frowning:

**Comment by benbalter** [comment]
@nschonni I know there were some recent changes to the Prose fork/pull request work flow... if you are able to reproduce the issue, chances are I introduced the bug, and would love you insight over in https://github.com/prose/prose.

Thanks again for the pull request. Looks like there's a conflict as a result of #34, but will get it merged shortly.

**Comment by nschonni** [comment]
I'll rebase now :wink:

**Comment by nschonni** [comment]
Rebased

**Comment by benbalter** [comment]
Ha. Once again beat me to it. :beers:

**Comment by nschonni** [comment]
No problem :smile: 
I'm not sure about the Prose stuff, because I have some machines it won't work on at all (work) and some that seem to have some quirks on (home FF24)

**Comment by nschonni** [comment]
The prose issue may be related to https://github.com/prose/prose/issues/597 but I'm not sure

**Pull request merged**
