### PR TITLE
Add Prose default metadata

### PR DESCRIPTION
**Pull request by nschonni**
Related to #101, but the submit.md wording needs to be decided on.

### CODE REVIEW

**Comment by nschonni** [comment]
Oops, need to fix up the label text. Will reopen

**Comment by nschonni** [comment]
Attached is how the new metadata modal looks with the explicit meta data fields
prose post metadata pop up

**Comment by benbalter** [comment]
Oh man. Much excellent. Should have done this originally. Thanks @nschonni

**Comment by nschonni** [comment]
No problem. The only catch right now is that the image upload has to be done using the story editor part (but it goes in the correct folder now).

**Pull request merged**
