### PR TITLE
Additional Treasury Board Secretariat repo

### PR DESCRIPTION
**Pull request by nschonni**
Used by the TBS GCTools group

### CODE REVIEW

**Comment by MaryBethBaker** [comment]
@nschonni What's up with this addition to the list? Why did Travis-ci get involved? Were you trying to automate the updates to the list? 

What's the plan?

**Comment by nschonni** [comment]
@MaryBethBaker I noticed this repo from https://github.com/canada-ca/welcome/pull/10, but updating this list here isn't automated right now. I think someone on the GitHub side has a script somewhere that uses something like https://github.com/benbalter/gman against the Organization owners to sniff out new orgs. The Travis-ci failure is from an org that has been deleted since the last time the site built. I'll do another PR for that

**Comment by MaryBethBaker** [comment]
@nschonni n00b here - are you using PR to stand for pull request? ;)

**Comment by nschonni** [comment]
@MaryBethBaker yup :100:, PR = Pull Request

**Comment by jbjonesjr** [comment]
Hi @MaryBethBaker . Yes, most of the orgs and GitHub users here are added manually. People from all over the 🌎 come to add their local, state, tribal, and national governments to the list.

Travis is used to make sure that everything is working like we expect it to based on the additions (but more often then not it alerts us that things that used to work no longer do).

**Comment by MaryBethBaker** [comment]
@jbjonesjr Thanks for the explanation. I appreciate that you took the time to help me learn this process. :+1:

**Pull request merged**
