### PR TITLE
Adding SSAgov and removing three 404 accounts

### PR DESCRIPTION
**Pull request by ghost**
=Organization:

**Your Organization**: _Social Security Administration_
**GitHub Organization url**: _@SSAgov_  
**Country/Locality**: _United States_

Inclusion requirements:
- [ ] Referenced account is an [Organization](https://github.com/github/government.github.com#add-organization) not a User^
- [ ] If this is a government project, your Organization's description should include a reference to your country/agency.
- [ ] Make sure your Organization includes at least one public repository
- [ ] Please also include a URL for your organization that links back to your organization or agency homepage.
 
^ If you want to convert your account to an org, details can be found here: https://help.github.com/articles/converting-a-user-into-an-organization/
  
 :heart: GitHub Government Contributors

### CODE REVIEW

**Comment by nschonni** [comment]
> Referenced account is an Organization not a User^

:sparkles: , but your account is a user not an organization

**Comment by SSAgov** [comment]
@nschonni You're correct....we're going to convert this account to an org account shortly. Should I leave the PR open or close it and create a new once it's done?

**Comment by nschonni** [comment]
I don't have the ability to merge anything, but i'd just leave it open and get one of the maintainers to just reset the build once it's done

**Comment by SSAgovAdmin** [comment]
SSAgov has been converted to an organization. Can one of the maintainers reset the build?

**Comment by jbjonesjr** [comment]
Thanks @SSAgovAdmin for patching `scalability-llnl` for us (and getting SSA into a proper org). @tgamblin or @IanLee1521 what happened to the above ☝️? Gone for good, or just moved elsewhere?

**Comment by tgamblin** [comment]
@jbjonesjr: everything in `scalability-llnl` moved to `llnl` circa 2015.  It had no more repos so I just deleted it.

**Comment by jbjonesjr** [comment]
@tgamblin 👍 . Makes sense, long live @llnl!

**Pull request merged**
