### PR TITLE
Added cleveland metroparks

### PR DESCRIPTION
**Pull request by smathermather**
Adding Cleveland Metroparks as a gov agency in the list of USA agencies.

### CODE REVIEW

**Comment by jlord** [comment]
Thanks @smathermather! Do you think it should go under US City though?

**Comment by smathermather** [comment]
Hmm, good question.  We're a "special district" or subdivision of the state, but we aren't state government either... .  Let me take another look.

**Comment by smathermather** [comment]
See if this makes more sense...

**Comment by jlord** [comment]
Thanks @smathermather! I'm good with that, hopefully there will be others in that group. As these pull requests come in we'll get a better idea of the scope and the subdivisions that make sense for organizing everyone. I'm super excited how many have come in!

**Comment by smathermather** [comment]
Thanks @jlord.  Re-arrange as you see fit.  "Special District" is very special and uncommon, even within the US, so maybe "Local" would be a better/more generic fit... .  Or I can change and redo the pull request.

**Pull request merged**
