### PR TITLE
Remove unused selectors.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
Can someone merge this? I'm working on stuff that will conflict with this...

**Comment by benbalter** [comment]
@XhmikosR if this is still relevant, would you mind merging in `gh-pages` to resolve the merge conflicts?

**Comment by XhmikosR** [comment]
Updated ready to merge.

**Comment by benbalter** [comment]
Thanks!

**Pull request merged**
