### PR TITLE
Create 2013-10-17-xas-software

### PR DESCRIPTION
**Pull request by bruceravel**
Create a _post for the Demeter package of software for XAS data analysis and processing, a project from a physicist at the United States' National Institute of Standards and Technology.

### CODE REVIEW

**Comment by benbalter** [comment]
@bruceravel really, really cool post (at least the part that I understood! :smile:!) and looking forward to working with you to get it published.

Have you had a chance to look at [the style guide](http://government.github.com/submit/style-guide/)? It was a bit hidden, so you may have missed it. Specifically, I'd love to focus our efforts on two things:
1. Keeping in third-person
2. Providing more context to why your approach was so innovative (which it is). What is the approach normally taken? How was this different? What was the result? 

The technical details are extremely cool, but for a non-brainiac crowd, which I'd imagine most of a readers are, providing more context into elements from your story, which may be similar to their current challenges may resonate a bit more.

**Comment by bruceravel** [comment]
@benbalter : Thanks for the comment.  I was becoming a bit concerned that government.github.com may not have been interested in scientific content.  So it is nice to get some feedback.

I have not, in fact, seen the style guide.  It was, apparently, sufficiently hidden to be missed by me. :smile: 

In the next few days I will find a few moments to edit my entry in light of the style guide and your two specific suggestions.  As I do so, I will be very interested to get your feedback on content as well as form.  I actually worry quite a bit about communicating science effectively to a non-scientist audience (I don't much care for your term -- I doubt I am any smarter than you.  The main difference is that I probably liked my physics class in high school more than you did.)  I am pretty certain that what I do can be made compelling for a broad audience, but feedback will help.

**Comment by bruceravel** [comment]
@benbalter : again, thanks for your feedback.  I put a bit of effort into my text, trying to follow more closely to the style guide and trying to make it a bit more readable for someone not like me.  I'd be grateful for some more feedback at this point.  Cheers!

**Comment by benbalter** [comment]
@bruceravel This is great, and much more "human readable" :smile:. I'd love to see if we can't get it posted this week some time.

It's your post, but one suggestion I might have would be to move the paragraph that begins "scientists from the" and the two paragraphs that follow (so in other words, the last three paragraphs) up above the first two. That way you can ease non-technical users into who you are and what the tool is, before jumping directly into the details of the process.

Either way, an awesome story and looking forward to helping to ensure it's told. Thank you for taking the time to put this together.

/ccing @github/science which is much smarter than me on this stuff and my be able to speak more intelligently on the subject.

**Comment by benbalter** [comment]
:heart: it.

The only thing left on my list would be if you had an image that we could associate with the post (see [government.github.com](http://government.github.com) for some examples from the other post. If you just drag and drop it into a comment here, I'll take care of getting things posted.

**Comment by bruceravel** [comment]
I asked a few of my science-y friends to give it a read and offer some feedback.  We'll see what they suggest.

I will think about a figure.  I don't have just the right thing for this context immediately handy, but I will work on it.

**Comment by bruceravel** [comment]
Art is not my strong suit, but here is what I came up with as an image.

logo_try2

**Comment by benbalter** [comment]
:heart: it.

[Posted at government.github.com/stories/xas-software](http://government.github.com/stories/xas-software/). Thanks again for taking the time to submit the pull request!

**Pull request merged**
