### PR TITLE
Update civic_hackers.yml

### PR DESCRIPTION
**Pull request by josephbleroy**
Added https://github.com/datapolitan to **civic_hackers.yml**.

> We're one of the few organizations teaching critical thinking and data literacy with open data to civil servants, helping build a workforce able to comprehend and use the vast streams of data already starting to flow into government agencies. With our project work, we're introducing open-source technologies to government, helping agencies conserve valuable financial resources and leverage broad communities of committed developers. In our strategy consulting, we're helping agencies develop the critical understanding of how data can be leverage to meet their operational needs, developing awareness of critical issues, and facilitating a broad understanding of the value data holds for leading organizations to success.

### CODE REVIEW

**Comment by nschonni** [comment]
This one is a user, not an organization

**Comment by josephbleroy** [comment]
@nschonni I believe it's an actual organization that provides services to civil servants in the NYC area. I know the owner, so I'll ask. I noticed a lot of the projects are collaborated on, and I believe it's a registered business in NYC. 

I'll clarify further.

**Comment by nschonni** [comment]
They'd need to follow https://help.github.com/articles/converting-a-user-into-an-organization/ to be included since this only list GitHub organizations

**Comment by jbjonesjr** [comment]
Hey @josephleroy , checking in on this PR. I'll leave this open for another 7 days for this to get resolved. Otherwise, I'll close this PR (but you are welcome to reopen it at a later date if the user gets changed to an organization).
Thanks!

**Comment by jbjonesjr** [comment]
ping @josephbleroy

**Comment by nschonni** [comment]
Looks like the org might be https://github.com/Datapolitan-Training

**Comment by jbjonesjr** [comment]
@josephbleroy and @datapolitan. It does look like `datapolitan-training` is the correct org. I'll be happy to merge an updated version of this, but I don't have rights to fix it. Can you either fix it or submit a new PR?

Also, @datapolitan, you should add a url and image to your Org to make it easier to verify.

Closing this as it's not-actionable for now. Feel free to reopen it once it's been fixed.

**Pull request closed without merging**
