### PR TITLE
add National Health Service of the UK

### PR DESCRIPTION
**Pull request by afeld**
**Your Organization**: National Health Service
**GitHub Organization url**: @nhsuk
**Country/Locality**: United Kingdom

Inclusion requirements:
- [x] Referenced account is an [Organization](https://github.com/github/government.github.com#add-organization) not a User^
- [x] If this is a government project, your Organization's description should include a reference to your country/agency.
- [x] Make sure your Organization includes at least one public repository
- [x] Please also include a URL for your organization that links back to your organization or agency homepage.

@AdamChrimes @beseven @sinclr4 @st3v3nhunt Seeing you on the [People](https://github.com/orgs/nhsuk/people) page - game to [add a description to the organization](https://help.github.com/articles/accessing-your-organization-s-settings/)?

### CODE REVIEW

**Comment by sinclr4** [comment]
Description for nhs.uk added

**Comment by chrimesdev** [comment]
@afeld Hi Aidan, is there anything more you need from us to get this PR approved?

**Comment by afeld** [comment]
Not that I can tell, thanks!

**Comment by jbjonesjr** [comment]
merging now that #749 is resolved.

Thanks everyone!

**Pull request merged**
