### PR TITLE
added NYCEDC (http://edc.nyc) to the list

### PR DESCRIPTION
**Pull request by mralexho**
NYCEDC has several datasets produced on a monthly basis from the Research & Analysis team. Datasets include Labor Force & Payroll, Travel & Tourism, Demographics, Real Estate & Construction, and more.

We'll be releasing these datasets and tools in the coming months.

### CODE REVIEW

**Comment by benbalter** [comment]
@mralexho is @NYCEDC a government agency? A non-profit?

**Comment by mralexho** [comment]
@benbalter it's a hybrid setup but for simplicity sake, it should be non-profit. I'm not entirely sure where I can place @NYCEDC. Would we fit under civic hackers?

**Comment by benbalter** [comment]
Civic hackers would probably make more sense, if you're able to make the change.

**Comment by nschonni** [comment]
@jbjonesjr this already landed in #335

**Pull request closed without merging**
