### PR TITLE
Update civic_hackers.yml

### PR DESCRIPTION
**Pull request by TOPWORKS-CZ**
```
TOPWORKS-CZ add
```

### CODE REVIEW

**Comment by nschonni** [comment]
This listing is for organization accounts, rather than individual accounts

**Comment by jbjonesjr** [comment]
Hey @TOPWORKS-CZ , as @nschonni mentioned, the list is for organizations, not individual users. if you want to convert the topworks account to an org, we could then include it. You can see documentation on this process here: https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by jbjonesjr** [comment]
Hey @TOPWORKS-CZ  , checking in on this PR. I'll leave this open for another 7 days for this to get resolved. Otherwise, I'll close this PR (but you are welcome to reopen it at a later date if the user gets changed to an organization).
Thanks!

**Comment by jbjonesjr** [comment]
Hey @TOPWORKS-CZ  , checking in on this PR. I'll leave this open for another 7 days for this to get resolved. Otherwise, I'll close this PR (but you are welcome to reopen it at a later date if the user gets changed to an organization).
Thanks!

**Pull request closed without merging**
