### PR TITLE
Added yourmapper as civic hacker

### PR DESCRIPTION
**Pull request by schnuerle**

### CODE REVIEW

**Comment by afeld** [comment]
This list is meant to showcase government organizations that have public repositories on GitHub.  Thanks anyway!

**Comment by afeld** [comment]
Sorry, scratch the part about limiting to government organizations in my last comment.  Do feel free to re-open once some repos have been added though!

**Comment by nschonni** [comment]
@afeld seems #47 seems to contradict that. Although the "Civic hackers" category could probably use some better guidelines

**Comment by afeld** [comment]
@nschonni I think our comments crossed paths - see [mine above](https://github.com/github/government.github.com/pull/38#issuecomment-26394678).

**Comment by nschonni** [comment]
Yup :wink: Agreed about the placeholder org though.

**Comment by schnuerle** [comment]
Yeah we do the same things as many of the orgs listed in the civic hackers category: work with govs, helped create an open data portal, hosted a transportation camp, organized our city's CfA brigade, won at the CfA hackathon, hosted the NDoCH hackathon, created a data standard, mapped city data in apps and sites, etc. 

Didn't know having repos was a requirement. I'll add what we have then reopen.

**Comment by afeld** [comment]
@schnuerle There aren't any public projects...therefore it isn't using GitHub for open source! :trollface:

Just giving you a hard time - we could probably use some language on the site to clarify what we are looking for in organizations to include them.  Looking forward to seeing your projects!

**Comment by schnuerle** [comment]
I've certainly used GitHub for open source.  I've pulled projects, deployed them, reported bugs, and have some private repos.  I was just following the instructions under "Add An Organization to the List". The Department of Commerce doesn't even have any repos https://github.com/commercegov

Just giving you a hard time :).  I'll make some repos public and move some over from bitbucket.

**Comment by schnuerle** [comment]
Can this be reopened, then merged?  I don't have permissions.

As requested, I've added 2 open source project repos to our git page and am working on 2 more.

Thanks!

**Comment by afeld** [comment]
:thumbsup: Just needs a merge from master.

**Comment by schnuerle** [comment]
So based on #74 do I have to prove that YourMapper is a "group focused on government" if it's not entirely clear?  

If so, here is my evidence:
- Is a repository of government open data: http://www.yourmapper.com/browse
- Provides open data and mapping services with GovMapper: http://www.govmapper.com/
- Created a municipal data standard used with city/county/state govs called Open Municipal Geodata Standard: http://www.omgstandard.com/
- Mapped data and helped create Louisville's Open Data Portal: http://blog.metromapper.org/2012/01/louisville-metro-partnership-crime.html
- Created and hosted a Transportation Camp for hacking local data: http://blog.metromapper.org/2011/12/louisville-transportation-camp-recap.html
- Participated in and won the Code for America Hackathon: http://blog.yourmapper.com/2013/02/winner-of-code-for-america-hack-a-thon/
- Was the host for our National Day of Civic Hacking event: http://blog.yourmapper.com/2013/06/hack-for-change-louisville-recap/
- Founded Louisville's Code for America Brigade: https://groups.google.com/forum/#!forum/civicdataalliance
- Has worked with our local bus transportation system to open their Transit Feed: http://blog.metromapper.org/2012/11/2nd-annual-louisville-transportation.html
- Tracks the status of open data across Kentucky: http://blog.metromapper.org/2012/11/open-data-in-kentucky-overview.html and http://blog.metromapper.org/2012/11/geospacial-open-data-in-ky-louisville-v.html

Hope that helps. Thanks.

**Comment by afeld** [comment]
@schnuerle No, it's as much a guide for us as it is for you.  Supporting evidence certainly helps, but usually it's easy to tell by looking at their repos or their website itself.

Per [my comment above](https://github.com/github/government.github.com/pull/38#issuecomment-26449980), I'm happy to merge this - just needs `master` merged in (or a rebase).

**Comment by schnuerle** [comment]
Ok, thanks.  Do you need me to merge master in, or do you all?

**Comment by jlord** [comment]
I took care of the merge with master. Thanks @schnuerle!

**Pull request merged**
