### PR TITLE
lazy-load the avatars on the community page

### LINKED ISSUE #664: improve page load speed
The page is getting slow to load, which is (I believe) almost entirely due to the number of avatars being loaded. I would suggest doing a lazy load of the images. There are a number of JavaScript plugins to facilitate this. Happy to take a pass at it, if interested!

### PR DESCRIPTION
**Pull request by afeld**
Closes #664.

Lazy-loads the images for a dramatically faster page load speed. Before:

screen shot 2018-03-31 at 10 59 03 am

After:

screen shot 2018-03-31 at 10 58 19 am

Waiting on jekyll-avatar to be updated on GitHub Pages.

cc @benbalter

### CODE REVIEW

**Comment by benbalter** [comment]
@afeld the update has been deployed. If you don't mind cleaning up the Gemfile, I believe we can finally merge this. Thanks again!

**Comment by afeld** [comment]
https://pages.github.com/versions/ is still showing 0.5.0...is that accurate?

**Comment by benbalter** [comment]
0.6 is currently deployed. Just rebuilt the page: https://pages.github.com/versions/?dontCache=1531326099311

**Comment by jbjonesjr** [comment]
@afeld I'll get the build working this week so either before or after the Gem is good to go, the build will be solid.

**Comment by afeld** [comment]
Away from my computer today, but made the edit from my phone 😊 Feel free to merge/edit the branch if it works for you!

**Comment by afeld** [comment]
Ok, updated the plugin, rebased, and confirmed it still works!

**Comment by jbjonesjr** [comment]
much lazy. such lode.

**Pull request merged**
