### PR TITLE
Convert to GitHub Actions

### PR DESCRIPTION
**Pull request by nschonni**
Trying this out to see if some of the unrelated build failures can be reduced. This uses `paths` to only run CI jobs based on what files are touched

### CODE REVIEW

**Comment by mlinksva** [comment]
Seems like a good idea. I think someone who is an admin for this repo will need to merge to get past failing (now nonexistent) Travis-CI check.

**Comment by nschonni** [comment]
Maybe @benbalter or @jbjonesjr

**Comment by benbalter** [comment]
I'm no longer an admin... are you @jbjonesjr?

**Comment by jbjonesjr** [comment]
thx @nschonni

**Comment by nschonni** [comment]
Thanks @jbjonesjr, I noticed on the latest PR that Travis probably still needs to be flipped off in the branch policy

**Comment by jbjonesjr** [comment]
Removed! Thanks for the 👀

**Pull request merged**
